### ISSUE TITLE
Key picker: Keyboard mode

### ISSUE THREAD

**Issue by Ariane-B** [Dygmalab/Bazecor#103]
**Is your feature request related to a problem? Please describe.**
When editing a key's behaviour in Bazecor, I always end up scrolling around a lot because I can't find a given key's category. My eyes will be darting left and right and I'll be scrolling up and down trying to find it, even though I know exactly what i'm looking for.

**Describe the solution you'd like**
Whether they like it or not (and if they bought a Dygma, they probably don't, but still), everyone's familiar with the layout of a big, full-featured keyboard. Something like this, for example.

![Logitech G19s, a huge keyboard](https://nerdtechy.com/wp-content/uploads/2015/01/Logitech-G19s-Gaming-Keyboard-with-Color-Game-Panel-Screen.jpg)

Modifiers are where you expect them, function keys are on top, the navigation cluster is on the right, and further right is the numpad with its familiar layout. PrintScreen is above the arrow keys. Media keys are on the top right, and the top and left parts house any non-standard functions.

I think Bazecor's "Key Config" menu should optionally be displayed as an illustration of a workspace with a classic large keyboard and a mouse, on which you could select functions. Less standard functions like layer or RGB related controls would be clustered above or at the left of the keyboard, in drop-down menus or something similar.

There could also be a search function that would highlight matches on the visual picker.

**Describe alternatives you've considered**
There are other ways the key picker could be improved. For instance, the keys could be searchable. The categories could be reworked. And those "keyboard agnostic" options should absolutely still be a thing. But nothing is ever going to be as intuitive as every long-time computer user's intuitive knowledge of where Shift, or "that one key above tab and to the left of 1" are, so I think a visual key picker is a must.

**Additional context**
I realize that it can sound preposterous to use a full-sized keyboard in a piece of software dedicated to a compact ergonomic keyboard. It may make you feel like you'd be promoting something wrong. But there's nothing more intuitive than a visual representation that you're familiar with.

It would be like if you made an entirely different split game controller that could be used on Windows. Your configurator software would *need* a visual representation of an Xbox controller to pick functions from, since that's the "original" thing you're mapping functions to, no matter how superior your product may be. If it didn't have a handy Xbox button picker, it'd just feel clunky to use.

**Comment by AlexDygma** [comment]
Hey @Ariane-B !

We are going to do two things to improve this:

- Use a feature other dygmate developed that allows you to search the keyconfig menu for any key #177
- Build a new interface that allows you to pick the keys from a full size keyboard which everyone knows

**Comment by Ariane-B** [comment]
Ooh, that sounds very promising! :)

**Comment by davidm2m** [comment]
@Ariane-B I think this is implemented in bazecor 1.0.0 betas, and if it is correct @AlexDygma it can be closed
