### ISSUE TITLE
Flashing screen does not close automatically when flashing process finishes

### ISSUE THREAD

**Issue by AlexDygma** [Dygmalab/Bazecor#108]
**Describe the bug**
When flashing a Raise with a new Firmware, Bazecor is unable to close automatically the flashing screen, it remains open and with the text UPLOADING... in a light grey color (disabled state) on the lower right button.

**To Reproduce**
1. Go to the flashing screen
2. Click on Update button
3. When appears, click on start countdown button and follow the steps to start the flashing process
4. When the process is finished, the modal window does not close and it remains open with the text UPLOADING greyed out in the button.

**Expected behavior**
The window should close on it's own indicating the user the process has finished successfully

**Screenshots**
Looking up the console, the process ends without errors and it stops outputting logs to the console when the restoring process ends, so nothing strange here.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Bazecor Version: 0.2.2

**Additional context**
Happens every time i try to flash the Raise

**Comment by eldelacajita** [comment]
Reproduced on Linux with Bazecor-0.2.3-BETA-5+104.

**Comment by AlexDygma** [comment]
Solved on #105 Beta 10
