### ISSUE TITLE
"Layer shift when held" won't type that same key if I type the next one too fast (Allow users to edit the time to trigger effect when held)

### ISSUE THREAD

**Issue by diogox** [Dygmalab/Bazecor#109]
**Describe the bug**
For my use case I'm assigning the key `s` the `Layer shift when held, normal key otherwise` functionality.

The problem is that sometimes when I'm typing words with the letter `s`, out of habit, I'll be pressing the next letter before I released the previous one (the letter `s`).

What this does is that it triggers a layer shift while `s` is held, causing the next key I press (let's say `e`), since it's a transparent key in the new layer, to type the letter `e`, but it doesn't type the letter `s`, because I pressed `e` without releasing `s`.

I understand this is the expected behavior. So this is as much a bug report as it is a feature request.

I think a way of fixing this would be to allow us to set an offset for the `Layer shift when held, normal key otherwise` functionality.
For example, we could set it to only trigger after the `s` key has been pressed for 500ms.

This is the most apparent solution to the problem, to me.

**To Reproduce**
1. Enable `Layer shift when held, normal key otherwise` for the key `s` to a layer where the key `e` is a transparent key.
2. Hold the key `s`.
3. Press the key `e`.
4. Release `s`.
4. You'll notice that `e` gets typed, but `s` (that was pressed before it) doesn't. When you're typing words really fast this becomes an issue.

**Comment by diogox** [comment]
Another solution would be to have a special type of key that would break you out of the layer shift and type all the keys you pressed while in that layer. But this sounds more convoluted..

**Comment by AlexDygma** [comment]
Hello @diogox ,

the key that breaks all modifiers is ESC, you can try pressing that one, but ill look into your problem so we can try solving it.

**Comment by diogox** [comment]
Breaking out of the layer isn't really the problem 😄

Please have a look and lmk if you think my suggestion makes sense as a feature request 🙂

Thanks!

**Comment by AlexDygma** [comment]
Hello again 😄 ,

After looking into the firmware, i think it might be possible to make this as an additional parameter added to the rest of them we already allow you to customize through bazecor preferences menu, i have already received other suggestions like adjusting the debounce for certain types of mechanical switches that may suffer of more debounce than others, etc.. so i'll change this bug report to a feature request so this concept of changing the time it takes to trigger the held effects on the keyboard.

**Comment by diogox** [comment]
Thanks :raised_hands: 

To be clear, I would prefer if this was a per-key effect, since this only affects me when using letter keys for layer-shifts. But I'll take a global layer shift offset over nothing :smile:

**Comment by AlexDygma** [comment]
Yay!

time has come, @diogox 

now we are merging an overall parameter, to make it key-wise we would have to use too much memory, so for now we are not going to implement it until we introduce more features.

**Comment by diogox** [comment]
Awesome! Thanks for letting me know! 😁
