### ISSUE TITLE
Double tap to Capslock/Numlock/Shiftto

### ISSUE THREAD

**Issue by davidm2m** [Dygmalab/Bazecor#115]
**Describe the solution you'd like**
Make possible block a key with a double tap, for example with normal click of shift key work as normal but when you push it two times block the Caps like a smartphone, I think that it can be userfull for people that use rarely capslock, like me, and wants to have a extra key to another function without loss the capslock3

I think that it can be userfull at shitto layer keys, because with a normal use you can pick the key for one use, but if you want to use, for examnple a shorcut layer, a lot of time without pushin the shitto key. For me a good example of it is if you need the numpad, to write a few number is better to have a shiftto key, but if you are using the calculator is better to lock it.

**Describe alternatives you've considered**

**Comment by fklement** [comment]
Yeah, I think this would be a pretty neat feature!

**Comment by davidm2m** [comment]
@AlexDygma I think that this funcionality is implemented with the One Shot modifier on bazecor 1.0.0, I think that this issue can be closed if you want.

**Comment by javierguzman** [comment]
I close this as this can be achieved with latest versions of Bazecor
