### ISSUE TITLE
Bazecor-0.2.3+119 Hold custom ESC key not working

### ISSUE THREAD

**Issue by paraduxos** [Dygmalab/Bazecor#120]
**Describe the bug**
When set `ESC` to non-default key, updating Bazecor would be failed. Since non-default `ESC` can't be hold while updating.

**To Reproduce**

1. Set `ESC` to somewhere else, eg. `thumb key`
2. Update Bazecor by holding that non-default `ESC`

**Expected behavior**
Firmware should be able to update.

**Desktop (please complete the following information):**

- OS: Windows 10
- Bazecor Version: 0.2.3+119

**Comment by AlexDygma** [comment]
Hello @paraduxos ! this is related to #117 and its already solved in it's pull request #118 so please get that default.hex file that has been updated and flash it with bazecor.

to get in bootloader mode you need to double press the button hidden at the back of the NEURON inside the small hole in the middle.

let me know if with this you can solve the issue.
