### ISSUE TITLE
Edit Numberpad Keys functions (Numlock Off)

### ISSUE THREAD

**Issue by Lite5h4dow** [Dygmalab/Bazecor#145]
**Is your feature request related to a problem? Please describe.**
The current issue is that the functions of the number pad buttons are laid out oddly

currently laid out as this
| | | |
|-|-|-|
1(end) | 2 (down) | 3 (page down)
4 (left) | 5 (?) | 6 (right)
7(home) | 8 (up) | 9 (page up)

which makes no sense given the layout

**Describe the solution you'd like**
I would like to be able to remap the function of the Numpad keys when num lock is disabled

**Describe alternatives you've considered**
I've already tried circumventing this issue with layers however I end up holding too many keys just to access the function keys for the Numpad

**Comment by alexpargon** [comment]
You should be able to solve this using Superkeys!
