### ISSUE TITLE
Bazecor 0.2.5 doesn't start on Big Sur 

### ISSUE THREAD

**Issue by ploffredi** [Dygmalab/Bazecor#147]
**Bazecor 0.2.5 doesn't start on Big Sur (0.2.4 version worked just fine)**

**To Reproduce**
1. Install the .pkg provided in Dygma web site
2. Try to start the application
3. The main window remain white
4. Press CTRL+SHIFT+I

**Expected behavior**
The application should start showing the available Dygma Raise keyboard

<img width="1197" alt="error" src="https://user-images.githubusercontent.com/7242756/100660475-5f0db200-3352-11eb-8c74-60ac43c9f044.png">

**Comment by rmaes4** [comment]
I too am experiencing this issue.

**Comment by timothyr** [comment]
I have encountered this error too.
MacOS BigSur version 11.0.1
Bazecor 0.2.5

**Comment by AlexDygma** [comment]
Hello!

Working on it, it seems apple requires this additional flag for bigsur 

com.apple.security.cs.disable-library-validation

Adding it to plist and compiling, will update the release wit the fix asap.

**Comment by AlexDygma** [comment]
Hello @ploffredi @rmaes4 @timothyr !

Hey guys, i have just released a new 0.2.5 dmg that fixes this issue, try it so we can close this issue! :)

https://github.com/Dygmalab/Bazecor/releases/download/bazecor-0.2.5/Bazecor-0.2.5.dmg

**Comment by ploffredi** [comment]
Hello @AlexDygma, it seems like the flag solved the issue. Thanks
