### ISSUE TITLE
Untrusted filee, app without signing

### ISSUE THREAD

**Issue by davidm2m** [Dygmalab/Bazecor#148]
**Describe the bug**
Windows 10 20H2 says that the software can damage my computer.

After download it, it ask me to conserv the untrusted file, and reply it again when I open it for the first time. This is an advice of Smart Screen.

**To Reproduce**
1. Download with, in my case, EDGE Chromium, and wait until finish.
2. It displays the message to conserv the file.
3. Open it to install and it says again the file is not secure because unsigned.

**Expected behavior**
Not show the messages.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Bazecor Version: 0.2.5

**Additional context**
Smart Screeen service is activated.

**Comment by AlexDygma** [comment]
Hello @davidm2m !

Unfortunately, we bought a certificate to sign our windows application but we haven't received it yet. as soon as we receive it we will sign the application and release it again.

**Comment by javierguzman** [comment]
I close this as nowadays Bazecor Windows releases are signed
