### ISSUE TITLE
Keyboard stops responding

### ISSUE THREAD

**Issue by JonathanDLowe** [Dygmalab/Bazecor#153]
**Describe the bug**
Keyboard stops responding/key presses are no longer registering. A mouse connected to the same hub still works. The lights remain lit, but nothing happens. This happens sometimes after not having touched the keyboard for a little bit and other times when I am actively browsing the web. It is fixed by replugging the keyboard.

**To Reproduce**
1. None, it just happens randomly.

**Expected behavior**
I expect the keyboard to keep working

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19041
 - Bazecor Version: 0.2.6

**Additional context**
I don't have much information, but I am filing the issue so I can get a list of information that would be helpful for debugging (windows events or logging) and steps on how to record to submit it when it happens again.

**Comment by AlexDygma** [comment]
Hey there @JonathanDLowe !

I'm sorry to hear you are having problems with the Raise, lets see if i can help you troubleshoot.

if you have a windows machine you can check the events at the events viewer that are related to USB periphery, but that will only be of assistance if something is going terribly wrong with the keyboard, first i suggest you to try to connect directly the keyboard to the computer, to try changing the main cable and to re-flash the latest firmware.

if any of this doesn't help getting it to work properly, then try to use Wireshark with USB messaging capture support to collect the telemetry shared between the keyboard and the USB stack from your computer, this may help you at least catch the error in a specific log.

**Comment by JonathanDLowe** [comment]
Thanks for the info. I reflashed the latest firmware. If it happens again, I'll look into setting up Wireshark for watching the USB messages.

**Comment by ploffredi** [comment]
I don’t know if this can be related but I have the same behaviour at home every time my refrigerator’s pump powers off (I know is quite bizarre 🤦🏼‍♂️) .... when happens immediately the keyboard stops responding I have to disconnect and reconnect the usb cable (tried several cables)

**Comment by AlexDygma** [comment]
So we managed to close this turning the freezing to restarts, we will keep working on this to minimize the impact of the freeze until it is no longer perceived.
