### ISSUE TITLE
Recursive macro call within the same macro breaks sending changes to the keyboard 

### ISSUE THREAD

**Issue by landonkim19** [Dygmalab/Bazecor#155]
**Describe the bug**
From the macro editor, It IS allowed to call macro 4 (as an example) itself from within the instruction of macro 4; once such macro is saved, sending the update to keyboard causes infinite loop (update never happens to keyboard, must manually disconnect the cable)

**Comment by AlexDygma** [comment]
Yes, this should be prevented on the editor as the keyboard has no  way to know he is entering a loop.
