### ISSUE TITLE
Bazecor loses configuration if system language is different to keyboard input

### ISSUE THREAD

**Issue by trankillity** [Dygmalab/Bazecor#156]
**Describe the bug**
I live in Australia, which uses British English for spelling (system language), and US English keyboard layout (ANSI).

When updating from firmware 0.2.4 to 0.2.6, my Raise lost its entire configuration and was identifying as ISO (UK) layout. It would not allow me to select ANSI (US) layout in Bazecor. I believe that the configuration clash is due to Bazecor querying system language rather than system keyboard layout, because I could only fix this issue by changing my system language to English US and reconnecting the Raise.

**To Reproduce**
1. Ensure System Language is set to British English and system keyboard layout is set to US English
2. Flash Raise firmware
3. Check Bazecor for configuration, note that layout is set to ISO, not ANSI. Also note that you cannot save configuration.
4. Change system language to US English
5. Reconnect Raise and re-open Bazecor
6. Note that the correct layout is now visible, and you can configure Raise again

**Expected behavior**
Bazecor is configured based on system keyboard layout, not system language.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.4 and 0.2.6

**Additional context**
I understand this may need to be the case for some EU countries, but Australia is definitely an issue.

**Comment by AlexDygma** [comment]
Hey there @trankillity !
This is strange, i flash ANSI Raise keyboards on a daily basis from PC's with European keyboard layouts and it doesn't reset itself, it even is capable of restoring the same configuration in either type.

When you update the firmware when being already in bootloader mode ( blue pulsing light on the neuron ), and then try to flash it, you can select both from ANSI or ISO when picking the keyboard, if you pick ISO, it will treat it as such. but that's the only instance that i can think of when this can happen.

If this wasn't your case, then you found a bug! and a very strange one, can you reproduce it? does it happen every time you update the keyboard?

**Comment by trankillity** [comment]
I have just re-flashed from 0.2.6 to 0.2.6 again with English (Australia) system language and English (US) keyboard language. The flash worked successfully this time, so unfortunately unable to reproduce. 

Was there perhaps some changes between 0.2.4 and 0.2.6 firmware/Bazecor that may have caused the mentioned issue? Any way that I can downgrade the firmware to check/help debug?

**Comment by trankillity** [comment]
Additional note: You mentioned that you flash in a similar fashion daily, but I'm assuming you always have multiple languages/input configurations installed. When the error occurred for me, I only had English (Australia) language pack installed, with English (US) keyboard layout installed. Perhaps it was because the additional languages weren't installed?

**Comment by AlexDygma** [comment]
Hey @trankillity !

Sorry for the late response 😓 

This issue is pretty weird as it affects only edge cases of user configuration on windows, i'll try to reproduce it locally.

**Comment by trankillity** [comment]
I've found a way to reliably reproduce it, and I believe it may even be intended functionality.

On a new connection of the Neuron, open Bazecor without either half plugged in, it detects as ISO - despite the configuration being that of an ANSI board. This does **not** happen if you have previously had the halve plugged in and disconnect them. It still detects properly as ISO then. This is on a cold star of the Neuron without having the halves connected.

There's a chance this is intentional as you guys are a EU company, so of course it should default to ISO however, it should really be defaulting to what the layout stored on the Neuron is.

**Comment by AlexDygma** [comment]
Hey @trankillity !

Well, the keyboard version is recognized on the sides, not in the neuron, to know if it has ISO or ANSI PCB's attached, it uses physical fuses on the sides that code the type of keyboard you are using, so if no side is attached, there is no configuration to tell the Neuron if it is a ISO or ANSI keyboard.

So it's not a matter of defaulting, but one of not having a configuration to use if the sides are not plugged in, as the keymap contemplates all keys (including iso and ansi variants) as different coded numbers, so they can coexist (and indeed they do, you can test it by loading saved ISO layers on an ANSI keyboard, and it will work without problems).

So probably we can't change this without adding more variables to the neuron that seem unneeded as the hardware fuses will always supersede them, unless you want to configure ANSI layouts without the sides.

**Comment by trankillity** [comment]
That makes sense. However, why does Bazecor recognise the keyboard as ANSI with only the Neuron connected it you have previously had the halves connected? Does it initialise some temporary variable/state when the halves get connected?

**Comment by AlexDygma** [comment]
Well, it seems that it has to send a identifier, and the enumerator that holds the keyboard identifiers starts with the ansi version, my money on a default [0] element being sent... 😆
