### ISSUE TITLE
Deleting macros doesn't update others accordingly

### ISSUE THREAD

**Issue by ASKemp** [Dygmalab/Bazecor#162]
When you have a list of macros, deleting one decrements the macro number of each of those after it but references to that macro don't also seem to be updated. 
E.g. have a list of Macro 0 to Macro 5
Delete macro 3 - macros at positions 4 and 5 now become 3 and 4 but references to macros 3,4 and 5 remain as they were.

**Comment by nyam-ii** [comment]
I can confirm this behavior. Maybe finding another method of referencing than the current index could help.

**Comment by Hugovdberg** [comment]
It appears this bug still persists in v1.0.0b15
