### ISSUE TITLE
Keyboard layout does not match keycaps for UK ISO Raise

### ISSUE THREAD

**Issue by PercussiveRepair** [Dygmalab/Bazecor#167]
**Describe the bug**
I raised this on the trello board before it was closed so I'm not sure what happened to it. 
The UK ISO Raise layout as configured by Bazecor does not match the keycap symbols for the numeric 2 and apostrophe keys as supplied on on the UK ISO Dygma Raise keyboard (keycaps mimic the MacOS key placement for " & @, not standard UK ISO placement see https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/KB_United_Kingdom.svg/1920px-KB_United_Kingdom.svg.png)
Numeric 2 has the @ symbol as the shift modified symbol on the keycap, but when pressed prints quotation mark. 
Apostrophe key has quotation mark as the shift modified symbol on the keycap , but when pressed prints @ symbol. 

**To Reproduce**
As above on UK ISO Dygma Raise
Numeric 2 has the @ symbol as the shift modified symbol on the keycap, but when pressed prints quotation mark. 
Apostrophe key has quotation mark as the shift modified symbol on the keycap , but when pressed prints @ symbol. 

**Expected behavior**
Shift modified symbol on the keycap should match output symbol printed

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: win10
 - Bazecor Version: observed on all versions so far, but I'm running 0.2.6 currently

**Additional context**
Ideally Bazecor should offer additional key options for numeric 2/@ and apostrophe/quotation marks to allow match of keys to keycaps.

**Comment by bcatly** [comment]
Hey there @PercussiveRepair. I also have the ISO layout, however, my keycaps are different. They might have supplied you with the wrong keycaps for those characters? I'd suggest contacting the customer support team and ask them about it.

**Comment by PercussiveRepair** [comment]
Thank @bcatly I've done that. However, I still believe this is an oversight/bug in Bazecor and think it needs addressing.

**Comment by bcatly** [comment]
@PercussiveRepair From what I understand, the way the keyboard interacts with the PC is in relation to the language setting you have turned on. By default, if you have yours set to English(UK), it will be 2 as " and ' as @. 

I believe the problem that occurred with yours is that they put the keycaps for the american layout for those keys on your Raise. As the keyboard uses the PC's language settings, I don't think there is a way to resolve that issue, unless you switch to English(US). However, this may skew some of your other keys. I may be wrong, but that's my understanding of it. Apologies if it isn't useful.

**Comment by PercussiveRepair** [comment]
Thanks for that clarification.
