### ISSUE TITLE
Dygma Raise stops responding 

### ISSUE THREAD

**Issue by carsonwoods** [Dygmalab/Bazecor#169]
**Describe the bug**
I have my raise plugged into a KVM usb switch, and occasionally it will just stop responding to all input. This issue appears to be similar, yet slightly different to issue #157. I also experience the issues in #157, but this has started happening more recently since the MacOS 11.2 update. A physical disconnect and reconnect of the keyboard to the switch fixes the issue. This issue is not consisntely reproducible, however it seems like it happens after periods of inactivity (though the computer does not necessarily go to sleep during this time). 

**Expected behavior**
The keyboard should stay connected and continue to recieve input at all times. 

**Desktop (please complete the following information):**
 - OS: MacOS 11.2
 - Bazecor Version: 0.2.6

**Additional context**
I use a Sabrent 2 Port USB Hub

**Comment by fklement** [comment]
Can confirm. Having the same issue.

**Comment by Acrossfy** [comment]
Try beta 0.2.7. It almost fixed this issue - freeze happens rarely and the keyboard automatically reconnects. The more info in DevBlog.

**Comment by carsonwoods** [comment]
It appears as though the 0.2.7 update does fix the issue. I'll close this issue.
