### ISSUE TITLE
Cannot tell when layers are switched when in rainbow mode

### ISSUE THREAD

**Issue by KaimTime** [Dygmalab/Bazecor#170]
Unsure if this is intended but when the raise is in either of the color shifting modes, switching layers doesn't visually change anything & as such it's impossible to tell which layer you are on.

If the feature to allow layers to shift between rainbow & distinct layer colorations was added that would extremely rad!
Or even the feature to allow us to assign the rainbow LED modes to a layer instead of just with the LED shift key.

**Comment by AlexDygma** [comment]
Hey @KaimTime !

That's a good one! i never took this into account but it has a bad solution on the FW side, so I'm tempted to link this to the idea that many users suggested, that is to have a background service that can show you the current layer configuration if a button is pressed on the raise.

it will show as an overlay on the O.S. and will disappear when you let go the button.

Do you think this will solve this issue for you?

**Comment by javierguzman** [comment]
OP did not reply to @AlexDygma  and this is gonna be covered by the overlay feature which is currently under our radar so I close this to avoid duplicates.
