### ISSUE TITLE
Bazecor-0.2.7.AppImage  doesn't start. 

### ISSUE THREAD

**Issue by pshanoop** [Dygmalab/Bazecor#171]
**Describe the bug**
I downloaded Bazecor-0.2.7.AppImage, It doesn't start. 
`/tmp/.mount_BazecozJyY2g/AppRun: line 45: /tmp/.mount_BazecozJyY2g/bazecor: No such file or directory`
I get this error message on terminal.

0.2.6 is working fine on same machine.

**To Reproduce**
Run the program from terminal

**Expected behavior**
Program to open up

**Screenshots**
![image](https://user-images.githubusercontent.com/1174257/107128997-58576a00-68c2-11eb-8a35-8ab280127e1d.png)

**Desktop (please complete the following information):**
 - OS:  Arch Linux
 - Bazecor Version: 0.2.7

**Comment by ChinaskiJr** [comment]
Same here for me. Also on Arch Linux : 
![image](https://user-images.githubusercontent.com/37048906/107157906-09bfd380-6987-11eb-83f0-c64c38e7f19c.png)

**Comment by NickLanger1990** [comment]
Also on Ubuntu 20.04.2 LTS:
![bug2](https://user-images.githubusercontent.com/45926167/107191335-4a9e0380-69ec-11eb-9016-1951da24f044.png)

**Comment by HomerSp** [comment]
Looks like maybe it wasn't generated properly for the release, because I just built it myself locally and it works just fine, so it should be a simple matter of rebuilding and reuploading it. Another interesting thing is that the released 0.2.7 AppImage is less than half the size of the generated one too.
Tagging @AlexDygma

**Comment by AlexDygma** [comment]
Hello Dygmates! I'll recompile it again with Travis to test if it does solve the problem!.

**Comment by AlexDygma** [comment]
Hey @pshanoop @ChinaskiJr @NickLanger1990! In fact, the Linux version weighed half that of the previous one, so it should be fixed now as i re-uploaded a new version! 

try to download again and test it! 😉

**Comment by pshanoop** [comment]
It works now.
