### ISSUE TITLE
Dark mode has white text on light background

### ISSUE THREAD

**Issue by yeungh** [Dygmalab/Bazecor#175]
**Is your feature request related to a problem? Please describe.**
When in dark mode, some text that's white has a light background with little contrast making it difficult to read. A good example of this is when going to update firmware, the text says "Your Raise is currently running version v.0.2.7." This is difficult to read due to the white text being on a very light grey background. 

**Describe the solution you'd like**
I'd like to see to see a darker background from the current shade to a darker one.

**Describe alternatives you've considered**
Switching to light mode is the easiest way to resolve the issue. 

**Additional context**

![image](https://user-images.githubusercontent.com/20916709/109373620-cf01da80-7864-11eb-939c-61699ad71524.png)

**Comment by GazHank** [comment]
I've proposed the following fix / enhancement for this:

[https://github.com/Dygmalab/Bazecor/pull/181](https://github.com/Dygmalab/Bazecor/pull/181)

please let me know if there are any other instances and I'll see if they can be fixed too
