### ISSUE TITLE
Macros limited to 33 and the last macro is shown the key code. 

### ISSUE THREAD

**Issue by nyam-ii** [Dygmalab/Bazecor#179]
**Describe the bug**
-Impossible to create new macros after the index 32. 
-When reaching the macro indexed by 32, clicking on "+" to create a new macro does nothing.
-When reaching the macro indexed by 32, "#24608" is shown on the graphic interface of the key instead of "Macro 32" and "Edit Macro" is replaced by a "Key code" text box in which "24608" is written and can be selected to be modifiable (text box). 

**To Reproduce**
1. Select a layer and a key
2. Click on "Key config"
3. Click on "Add macro"
4. Click on "Edit macro"
5. Click on "+" in the "Add new Macro" row at the end, until 33 macros are created (index 32), which is the limit
6. Realize nothing happens when clicking on "+" of the step 5 when the limit is reached.
7. Select the macro "32" and Click on "Apply & Exit" to come back at the main UI of the layer. 
8. Realize that the key doesn't have "Macro 32" but "#24608" as a "key code" and there isn't a "Edit macros" option anymore.

**Expected behavior**
To not have that "#24608" and also be able to create more than 33 macros. 

**Screenshots**
![Screenshot from 2021-03-14 12-20-01](https://user-images.githubusercontent.com/47141158/111076452-9d3b7580-84ec-11eb-986b-01d1bd098f68.png)
![Screenshot from 2021-03-14 14-38-06](https://user-images.githubusercontent.com/47141158/111076478-b3493600-84ec-11eb-9e3f-0e1e37fbe715.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS, 64-bit, GNOME Version : 3.36.8
 - Bazecor Version: 0.2.7

**Additional context**
I use Windows 10 (for gaming) and Linux for work/study. And I've used the Bazecor 0.2.7 on both OS' to create macros. (Macros created on Windows 10 don't have names in the app on Linux, and vice versa)

**Comment by kkckrnz** [comment]
I can confirm. When I create macro 32, the key code displays `#24608` and it is actually the same as macro 0.

**Comment by AlexDygma** [comment]
Hey @nyam-ii @kkckrnz !

Yes, this is not a bug, but a limited functionality ( i will leave it as a bug nonetheless)

the real reason for limiting the number of macros here is to prevent users form using more memory than available, to avoid this we should make a memory calculator that shows the actual consumption of the available memory for the macros

the total memory available right now is 2048bytes, each command uses between 2 to 6 (* 8) bytes depending on the command, to send a character you only need 2, to make a delay 3, etc... this means it's fairly easy to get to the 2048 hard limit on which you would start to get out of the memory boundaries for the macros.map (you have 64bytes per macro, so like 32 characters or like 20 characters with additional commands)

to avoid having memory problems i hard capped the limit to 32 macros as an overall, to fix this we will add a memory graph to show you how much memory your macros occupy and what you have left, not letting you add commands or new macros when you reach the limit.

but this is not easy and we are going to make more profound changes to the interface before fixing this.

if you really know this limit and want to work around it, just edit clone the repo, change the hard cap number to 64 (ex) and bear in mind you wont be able to make long macros for each of them.

btw, this is not very far away on the priority list 😄

**Comment by AlexDygma** [comment]
Hey @nyam-ii and @kkckrnz ! 

Guys, I'll push this to 64 as you should have enough with 10 to 15 actions per macro as an overall number for all of them ( you can still make limitless macros, but don't push them all ahead), on later revisions, i will implement the memory viewer so we can show you exactly how much you have left and block the creation of more macros when there is no available memory for them.

**Comment by nyam-ii** [comment]
Hey @AlexDygma , 

Thank you very much for the explanation and for raising the macro limits ! 

I suspected that there was an internal memory limit (as do all programmable keyboards) ! And the memory viewer will be a nice implementation !

Just as curiosity, do you know if there will be a new "neuron" with more memory (and USB ports?) as an hardware upgrade? 

Thanks in advance !
