### ISSUE TITLE
HUD for Selected Layer

### ISSUE THREAD

**Issue by rbergeron81** [Dygmalab/Bazecor#180]
**Is your feature request related to a problem? Please describe.**
No [...]

**Describe the solution you'd like**
Add an option to program a keystroke to show a semi-transparent heads up display on screen of the currently selected layer layout.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
Sometimes you forget the layout of the different layers, especially when you have many layers setup. It would be useful for learning your different layers on the fly.

**Comment by AlexDygma** [comment]
Hey @rbergeron81 !

this issue is linked to #170, so we will go ahead probably with your suggestion which helps you in more than one way.
