### ISSUE TITLE
Compose key

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [Dygmalab/Bazecor#183]
Please, add a dedicated compose key (like in LK201 keyboards of VT220 terminals) in Bazecor, so that we don't have to sacrifice a common key.

**Comment by AlexDygma** [comment]
Hey @massimiliano-della-rovere !

The possible key's to use on the raise are described on the HID descriptor implementation, but i cannot find the key that you are suggesting.

https://github.com/keyboardio/KeyboardioHID/blob/e7d840aa62f15a86afa84e164e27f8af3e74a508/src/HIDTables.h

there are the HID tables, if you find it please tell me and we will push it to the lineup!

**Comment by jeancroy** [comment]
I've seen a few place that suggest compose key is 0x65 keyboard application.

**Comment by GazHank** [comment]
@jeancroy & @massimiliano-della-rovere if 0x65 is the right key code then it looks like it is mapped to "Menu" which you can find in the navigation section:

![image](https://user-images.githubusercontent.com/64541249/115250812-d5ecf100-a121-11eb-9357-befd29deaea6.png)

Let me know if this doesn't work

Cheers

Gaz

**Comment by AlexDygma** [comment]
Hey @massimiliano-della-rovere !

when i searched for the compose key, it appeared to be something present on very old keyboards, not the menu key! the menu or APP key has been present since before summer, so i didn't relate them.

ill close this issue then!

**Comment by massimiliano-della-rovere** [comment]
ok

Il giorno mar 20 apr 2021 alle ore 09:43 AlexDygma ***@***.***>
ha scritto:
