### ISSUE TITLE
OSM are broken with dual use key

### ISSUE THREAD

**Issue by jeancroy** [Dygmalab/Bazecor#184]
**Description**
One shot modifier are consumed *immediately* when a dual use key is pressed.
That is, even before the dual use key has decided which input it will send.

**Reproduction  and expected behavior**
Example 1:

- Type OSM (for example shift).
- Type dual use key (for example e / shift to 1)

Expected Result: "E" (shift-e)
Current Result: shift, e (modifier is released before letter)

Example 2:

- Type OSM (for example alt).
- HOLD dual use key (for example space / shift to 1)
- Type key (for example 4 is mapped to f4 on that layer)

Expected Result: (alt-f4)
Current Result: alt, f4 (modifier is released before keypress)

**Comment by jeancroy** [comment]
So it seems that behavior where OSM cancel out with dual keys is due to plugin order.
https://github.com/Dygmalab/Raise-Firmware/blob/017da140d81b975afc14dcc0aa8aac5e92db5442/Raise-Firmware.ino#L207

`Qukeys` should be above `OneShot` with a recommendation to put it before `TapDance`
https://github.com/keyboardio/Kaleidoscope/issues/905#issuecomment-807467876_

**Comment by AlexDygma** [comment]
Hey @jeancroy !

good to see you found the issue! 😆 ill make the change for 0.3.0!
