### ISSUE TITLE
Bazecore fail to display Shift+Gui, showing #999999 instead

### ISSUE THREAD

**Issue by jeancroy** [Dygmalab/Bazecor#191]
**Description**
Most modifier combo have a nice form display like A+C+Key.
Shift+Gui works but display as #999999

**To Reproduce**
1. Assign a letter to a key
2. Check the checkbox for both shift an gui

**Expected behavior**
Display S+G+Key

**Desktop (please complete the following information):**

Tested on bazecor 0.2.7.1 +201.
Fixed in latest Chrysalis. 

**Additional context**
When choosing combinations of k elements out of n, the number of combination is expressed using binomial coefficient.
Given 5 modifers there's [10 different way to pick pairs of them](https://www.wolframalpha.com/input/?i=binomial%285%2C2%29) 

However there's only 9 of those 10 combo in the code, with shift+gui missing.
https://github.com/Dygmalab/Bazecor/blob/development/src/api/keymap/db/digits.js#L161-L169

It seems to be a purely graphical bug.
I pointed to digits but it's also missing from letters and possibly others.

**Comment by GazHank** [comment]
It looks like Ctrl+Shift+AltGr+Gui is missing too.

I think I've got a patch to all of the impacted files but will take another look to check I haven't broken anything :-)

**Comment by GazHank** [comment]
Fixed in 0.3.2 :-)
