### ISSUE TITLE
OSL

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [Dygmalab/Bazecor#200]
1st gen Raise, firmware 0.3.1.

Layer 0: physical key "left ctrl" is an OSL to Layer1.
Layer 1: physical key "left Linux" is an OSL to Layer2, which contains EXCLUSIVELY macros.

Press "left ctrl", then (in layer 1) double tap "left linux" without releasing "left ctrl", now you are in Layer 2 and you can release "left ctrl".

That's it! The only way to go back to Layer 0 is unplugging and replugging the Neuron from the PC or have a "move to Layer 0" key in Layer 2.

In Layer 1 the "left control" is transparent.
In Layer 2 both the "left control" and the "left linux" are transparent.

**Comment by AlexDygma** [comment]
Hey @massimiliano-della-rovere !

> 1st gen Raise, firmware 0.3.1.
> 
> Layer 0: physical key "left ctrl" is an OSL to Layer1.
> Layer 1: physical key "left Linux" is an OSL to Layer2, which contains EXCLUSIVELY macros.
> 
> Press "left ctrl", then (in layer 1) double tap "left linux" without releasing "left ctrl", now you are in Layer 2 and you can release "left ctrl".
> 
> That's it! The only way to go back to Layer 0 is unplugging and replugging the Neuron from the PC or have a "move to Layer 0" key in Layer 2.
> 
> In Layer 1 the "left control" is transparent.
> In Layer 2 both the "left control" and the "left linux" are transparent.

I have a question for you, why don't you held "left linux" instead of double tapping it? when double tapping a OSL button, you are telling it to move to that layer 😮, so i think that's what you are experiencing, but correct me if i'm wrong! 

By the way, you don't need to hold a OSL button, just to press it once, if you hold it, you are using it in fact as a shift to layer button!

Hope this helps! 😉

**Comment by massimiliano-della-rovere** [comment]
There's a difference between moving and double tapping: when you double
tab, if you tap again you go back to the previous layer. But it's not
happening.

Il giorno mer 14 apr 2021 alle ore 14:05 AlexDygma ***@***.***>
ha scritto:

**Comment by AlexDygma** [comment]
Now i have been able to reproduce it!

indeed if you tap once, the effect only lasts for a short while, if you tap twice, the layer switch is permanent, if you tap a third time, it should get you back to layer 0.

but what's happening is that between layer 0 and 1 the OSL behaves as expected (at least for me) but between layer 1 and 2, the button no longer behaves as it should with the third click. it wont return back to it's original layer.

Ill try to look into it. did this happen before?

**Comment by massimiliano-della-rovere** [comment]
I'm trying a new layout that brought this to the light.

I do not know whether iI happened before 0.3.1 to.

Il mer 14 apr 2021, 16:54 AlexDygma ***@***.***> ha scritto:
