### ISSUE TITLE
Enhancement request: Remove desktop shortcut

### ISSUE THREAD

**Issue by GazHank** [Dygmalab/Bazecor#206]
**Is your feature request related to a problem? Please describe.**
_Minor annoyance:_ During installation a desktop shortcut is created.  There is no option to disable this during the installation process.

**Describe the solution you'd like**
It would be nice if the installer didn't add yet another icon to the desktop.

**Describe alternatives you've considered**
An option during the install process could allow the user to choose to enable or disable the creation of a desktop shortcut, but I really don't think this is necessary.  I really don't know of anyone who likes shortcuts being dumped on their desktop.  I suppose I could write a little cron script to trash any shortcuts that are placed on the desktop, but that seems like a silly solution.

**Additional context**
If I build the app locally (yarn build:win) the installer doesn't generate a desktop shortcut, so it would appear that the process of creating the files for publication on Github uses a slightly different process.  Perhaps the electron build config is different on that machine?

The option to disable desktop shortcut seems to be createDesktopShortcut = false according to 
 https://www.electron.build/configuration/nsis

**Comment by alexpargon** [comment]
This has been disabled in the latest builds after updating Electron-Forge to the latest version
