### ISSUE TITLE
Keyboard sends cmd+c instead of cmd+option+\

### ISSUE THREAD

**Issue by wAuner** [Dygmalab/Bazecor#210]
**Describe the bug**
macOS BigSur English US Layout

When I press `alt + option + \` it sends `cmd + c` for copy. I really don't know why, I haven't changed much yet from the default configuration. See the screenshot for my current configuration.

**To Reproduce**
Select text on macOS and press `alt + option + \` and then paste that text.

**Expected behavior**
It should send the pressed keys, not something totally different.

**Screenshots**
<img width="1092" alt="Screenshot 2021-04-23 at 07 11 03" src="https://user-images.githubusercontent.com/18383180/115821429-12ab3780-a403-11eb-8c4d-57dfb16e0645.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Bazecor Version: 0.3.3

**Comment by GazHank** [comment]
Hi @wAuner would you be able to check that you don't have any other software remapping or intercepting the keystrokes?

When I search online for people facing similar issues issues I keep seeing references to Alfred and similar software changing the default/ expected mappings for some key combinations and [guides to change mappings](https://www.alfredapp.com/help/troubleshooting/cmd-alt-c/)

Would you be able to double check that you don't see the same problem if you use an alternative keyboard

Many thanks

Gaz

**Comment by wAuner** [comment]
@GazHank sorry 🙏, forgot to close this issue here as well. The problem was because alfred remappedthe keys, not the keyboard.

**Comment by GazHank** [comment]
Cool thanks @wAuner
