### ISSUE TITLE
App crashes on macOS

### ISSUE THREAD

**Issue by wAuner** [Dygmalab/Bazecor#213]
**Describe the bug**
<img width="372" alt="Screenshot 2021-04-26 at 12 52 07" src="https://user-images.githubusercontent.com/18383180/116071657-aab45580-a67d-11eb-88d9-520b584440d3.png">

**To Reproduce**
unclear

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Bazecor Version: 0.3.3

**Comment by GazHank** [comment]
@wAuner the lovely cryptic error message looks like it might be getting triggered by the code we use when the dark mode is changed.  Could you confirm if it is triggered when you swtich theme?  (either changing the setting within the preferences menu, or changing you OS theme settings?)

If you can confirm if that is the case, or share any extra info that would be really helpful as I don't have access to a Mac to reproduce the error myself

@AlexDygma within the current build config we still have the mac  settings as:

https://github.com/Dygmalab/Bazecor/blob/d79cfb2ebedf0d53261c5c25eb7445e8ca58c32e/package.json#L43-L44

Do you think that could be involved in this issue?

Many thanks

Gaz

**Comment by wAuner** [comment]
Sorry for the delay, my Dygma needed to be replaced. I've tried switching the theme, but that didn't trigger the issue. As far as I can remember, I really did nothing other than letting Bazecor run in the background. Since I got the new one, I wasn't able to reproduce the error. I'll observe it over the next few days and close the issue if doesn't happen again.

**Comment by AlexDygma** [comment]
So, i have been checking this for the new Beta 15 release and i think it should be solved with some additional checks i added, can you test it with it? here you go:

https://drive.google.com/file/d/1QGUBytckhbwaleg_HXWeJKnsAX8R3PpZ/view?usp=sharing

**Comment by AlexDygma** [comment]
👏 👏
