### ISSUE TITLE
"Bazecor.app" cannot be opened because the developer cannot be verified (MacOS Catalina)

### ISSUE THREAD

**Issue by iryan2** [Dygmalab/Bazecor#23]
![image](https://user-images.githubusercontent.com/5858312/71609706-738f7a80-2bd6-11ea-81bf-9c78c8f87fd9.png)

Downloaded from the MacOS dropbox link on https://www.dygma.com/myraise/

MacOS Version 10.15.2

**Comment by UngererFabien** [comment]
Hello, while waiting for Bazecor to be verified you can open it following this steps: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

1. In the Finder  on your Mac, locate the app you want to open.

Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.

2. Control-click the app icon, then choose Open from the shortcut menu.

3. Click Open.

The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.

**Comment by AlexDygma** [comment]
This was solved using notarization for the App, it's now working as intended
