### ISSUE TITLE
Provide MacOS `fn` key option

### ISSUE THREAD

**Issue by abangser** [Dygmalab/Bazecor#242]
**Is your feature request related to a problem? Please describe.**
While I am easily able to program specific function numbered keys (e.g. `f1`), there are some other uses for the `fn` key on a mac keyboard including `fn+del` to delete things from the finder window without having to use a mouse. 

**Describe the solution you'd like**
I would like a specific option for `fn` rather than just for each numbered function key.

**Describe alternatives you've considered**
I have tried to use the different combinations of del and backspace for the same behaviour but been unable to get the functionality of deleting from finder.

**Additional context**
n/a

**Comment by tino** [comment]
Any chance this will be implemented? I really need this to be able to swap between the built in keyboard and my Raise without too much cognitive stress :).

**Comment by alexpargon** [comment]
This is an issue, the fact is that we tried and got stumped into legal issues, it seems that the `fn` key in Mac keyboards is proprietary stuff, so you cannot trigger it unless your keyboard identifies as a Mac keyboard, to read more about this, you can take a look [here](https://gist.github.com/fauxpark/010dcf5d6377c3a71ac98ce37414c6c4)

So no chance of implementing this officially, sorry :(
