### ISSUE TITLE
Flashing instructions invisible with UI on dark mode

### ISSUE THREAD

**Issue by brandonchinn178** [Dygmalab/Bazecor#243]
**Describe the bug**
My system is set up with dark mode, and when trying to flash the new 1.0 firmware, the instructions are in white font against a white background. Highlighting the text shows it up.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2021-07-21 at 9 57 08 PM](https://user-images.githubusercontent.com/6827922/126591989-dc8c5ea0-b5c7-4bf5-a1d4-7cce12cda03b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Bazecor Version: 1.0-beta

**Additional context**

**Comment by QuaternionMark** [comment]
This appears to have been fixed in 1.0.1.

**Comment by javierguzman** [comment]
Close this as it should be fixed
