### ISSUE TITLE
api to interact with layers

### ISSUE THREAD

**Issue by yangkennyk** [Dygmalab/Bazecor#244]
**Is your feature request related to a problem? Please describe.**
kinda I suppose. 

- Would like to have layers auto switch based on the current focused app
- Would be able to create more advanced configurations that are no possible with bazecor currently by using karabiner.

**Describe the solution you'd like**
a way to switch layers with a terminal command. For example
`bazecor -ml 2` would move to layer 2
`bazecor -sl 2` would switch to layer 2
`bazecor -l` would return the current layer as an integer

ml = move layer
sl = shift layer

**Describe alternatives you've considered**
support sent me this

> The user needs to connect to the serial console of the keyboard (mind that doing this will make Bazecor unable to communicate with the keyboard due to a port occupied error while this channel is open)

so ideally I wouldn't have to lock up bazecor in order to send commands

**Comment by trankillity** [comment]
This would be a pretty useful function. A friend just described a use-case where this would be required: Automatically toggling a certain layer while there is mouse movement. Would likely be best to be spun off into it's own app however.
