### ISSUE TITLE
More Media Keys... I almost forgot how many thre are in total!

### ISSUE THREAD

**Issue by ryanerwin** [Dygmalab/Bazecor#257]
I had almost forgotten how many great media keys were available on some of the Windows 95 era keyboards...
There were so many shortcuts available on some vintage keyboards.....

For me, the ideal Dygma Keyboard would be Raise, but with a real tilde/backtick next left of the <kbd>1</kbd> key, and then the top row with <kbd>Esc</kbd> starting the <kbd>F1</kbd> - <kbd>F12</kbd> row, with keycaps for F1 - F12 that all double as Media Keys... If I could get more keys beyond that, would be fantastic. Key Caps that label the most popular media keys though frees up more human memory space to make other shortcuts.

![image](https://user-images.githubusercontent.com/2156415/131237772-af740f18-0d78-4776-b143-5da1976019f3.png)

![image](https://user-images.githubusercontent.com/2156415/131237715-9e4eadc9-bdd8-48d8-a6ab-43bddb337ad0.png)

You can get a list of all the Linux supported media keys with:

```
xmodmap -pk|grep XF86
```

Even more are listed here:

https://titanwolf.org/Network/Articles/Article?AID=c7fb3f42-8f04-4d06-b1be-b98abffa6b13#gsc.tab=0

```
XF86AddFavorite
XF86ApplicationLeft
XF86ApplicationRight
XF86AudioForward
XF86AudioMedia
XF86AudioPause
XF86AudioPreset
XF86AudioRecord
XF86AudioRewind
XF86Away
XF86Back
XF86Battery
XF86Bluetooth
XF86Book
XF86BrightnessAdjust
XF86CD
XF86Calculator
XF86Calendar
XF86Clear
XF86ClearGrab
XF86Close
XF86Community
XF86ContrastAdjust
XF86Copy
XF86Cut
XF86DOS
XF86Display
XF86Documents
XF86Excel
XF86Explorer
XF86Favorites
XF86Finance
XF86Forward
XF86Game
XF86Go
XF86History
XF86HomePage
XF86HotLinks
XF86KbdBrightnessDown
XF86KbdBrightnessUp
XF86KbdLightOnOff
XF86Launch0
XF86Launch1
XF86Launch2
XF86Launch3
XF86Launch4
XF86Launch5
XF86Launch6
XF86Launch7
XF86Launch8
XF86Launch9
XF86LaunchA
XF86LaunchB
XF86LaunchC
XF86LaunchD
XF86LaunchE
XF86LaunchF
XF86LightBulb
XF86LogOff
XF86Mail
XF86MailForward
XF86Market
XF86Meeting
XF86Memo
XF86MenuKB
XF86MenuPB
XF86Messenger
XF86MonBrightnessCycle
XF86Music
XF86MyComputer
XF86MySites
XF86New
XF86News
XF86Next_VMode
XF86OfficeHome
XF86Open
XF86OpenURL
XF86Option
XF86Paste
XF86Phone
XF86Pictures
XF86PowerDown
XF86PowerOff
XF86Prev_VMode
XF86Q
XF86RFKill
XF86Refresh
XF86Reload
XF86Reply
XF86RockerDown
XF86RockerEnter
XF86RockerUp
XF86RotateWindows
XF86RotationKB
XF86RotationPB
XF86Save
XF86ScreenSaver
XF86ScrollClick
XF86ScrollDown
XF86ScrollUp
XF86Search
XF86Send
XF86Shop
XF86Sleep
XF86Spell
XF86SplitScreen
XF86Standby
XF86Start
XF86Stop
XF86Support
XF86Suspend
XF86Switch_VT_1
XF86Switch_VT_10
XF86Switch_VT_11
XF86Switch_VT_12
XF86Switch_VT_2
XF86Switch_VT_3
XF86Switch_VT_4
XF86Switch_VT_5
XF86Switch_VT_6
XF86Switch_VT_7
XF86Switch_VT_8
XF86Switch_VT_9
XF86TaskPane
XF86Terminal
XF86ToDoList
XF86Tools
XF86Travel
XF86Ungrab
XF86User1KB
XF86User2KB
XF86UserPB
XF86VendorHome
XF86Video
XF86WLAN
XF86WWAN
XF86WWW
XF86WakeUp
XF86WebCam
XF86WheelButton
XF86Word
XF86XF86BackForward
XF86Xfer
XF86ZoomIn
XF86ZoomOut
XF86iTouch
```

I think the following are already complete:

(Dygma Bazecor Names / XF86 names)

```
MUTE - XF86AudioMute
TRACK + - XF86AudioNext
TRACK - - XF86AudioPrev
VOL + XF86AudioRaiseVolume
VOL - XF86AudioLowerVolume
STOP - XF86AudioStop
PLAY - XF86AudioPlay
BRIGHT + XF86BrightnessUp
BRIGHT - XF86BrightnessDown
EJECT - XF86Eject
CAMERA - XF86WebCam
CALC - XF86Calculator
(mouse) FORWARD XF86Forward
(mouse) BACK XF86Back
```

**Comment by erwin** [comment]
Just a reminder that the new version of the UI does look fantastic, but it still only covers a very small subset of the possible media keys...

Perhaps a user defined code / label would be an easier way to go...

![image](https://user-images.githubusercontent.com/11534217/168407369-95d5ffcf-685c-4195-9bc1-baedf8ba394e.png)

**Comment by javierguzman** [comment]
Hello @erwin what media keys are you missing?

**Comment by ryanerwin** [comment]
The Media & LED section looks great. I think you have most of the most commonly used keys now.

Here you can see a list of all the X11 supported media keys, used on various keyboards over the years:
https://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols

Rather than adding this huge list of possibilities, I would personally just prefer a way to add my own custom key codes...

**Comment by javierguzman** [comment]
There are people who has mentioned before the ability to use ASCII codes but what you are mentioning I believe is different. Also, the list you have posted is not a standard by any means as far as I have understood right? I mean, it is not like ASCII or unicode, it is only in the X11's world. Just asking for a deeper understanding

**Comment by afestini** [comment]
Just randomly adding my own interest in some extra media keys, specifically "Browser Home" and "Email". Probably my most used special keys and with Calculator already being covered, I'm only two keys away from finally getting rid of AHK.

I thought about directly setting keycodes in the json files, but I'll have to get a better understanding of those first.

**Comment by alexpargon** [comment]
Im going to add to the roadmap a way to put up a custom keycode for a key, it wont be recognized for now as adding all of the x86 keycodes will require a ton of UI work from @thiagohernandez.

Will also add a keycode list with the x86 key list above translated to kaleidoscope's keycodes for ease of use.

**Comment by erwin** [comment]
> way to put up a custom keycode for a key

That's fantastic news! Can't wait!

**Comment by alexpargon** [comment]
@erwin There you go! now you can add custom keys with the keycode and there is a specific explanation on how to add consumer keys (which are the ones mapped as media keys)
