### ISSUE TITLE
"sudo" is required to see the keyboard on Linux

### ISSUE THREAD

**Issue by pnomolos** [Dygmalab/Bazecor#26]
**Describe the bug**
In order for a scan to show up the keyboard on Linux you need to launch via sudo (or presumably added to a certain group, haven't done enough research yet to figure out which one that is).

**To Reproduce**
1. Launch Bazecor on Linux without elevated privileges.
2. Scan for keyboards (nothing shows up)

**Expected behavior**
Scanning for keyboards without elevated privileges should either ask for privilege escalation or just work.

 - OS: Ubuntu 19.04
 - Bazecor Version: 0.1.2

**Comment by cjdmax** [comment]
same issue; had to build from source and sudo execute the /dist/linux-unpacked, all because I was too lazy to find out which group to put my user account in or find out how to get the AppImage to work. I'll have another stab at it tonight.

**Comment by acron0** [comment]
Same issue on 18.04 LTS

**Comment by mattvenn** [comment]
This should work to add you to the correct group: sudo usermod -a -G dialout $USER
You also probably want to stop modemmanager interfering with the serial port after its first detected. I usually just uninstall it.

**Comment by algernon** [comment]
The best we can do in this case is to present a more informative error message, that points to a troubleshooting page.

**Comment by zalohasa** [comment]
This is not an issue in Bazecor. This is a problem of the default permissions your distro applies to your user. As @mattvenn said, you need to be in the right group to be able to write to the serial ports without root permissions. For arch for example, you need to be in the uucp group. In Ubuntu, you need to be in the dialout group. 
You can do "ls -la /dev | grep ttyACM0" and check the group the port is in.

**Comment by acron0** [comment]
> This is not an issue in Bazecor
It may not be a software problem but it's a UX problem that there is no information. As the OP suggested, the ideal fix would be a prompt. At the very least there should be a note on https://www.dygma.com/myraise/ about this.

**Comment by godlike64** [comment]
I just had this problem, and thanks to this github issue I was able to solve it. Not that it really matters, but on Gentoo, uucp is also the group used for /dev/ttyACM0.

Neither Bazecor 0.1.0 (downloaded from Dygma's website) nor Bazecor 0.2.0 (built from source from this repo) points to what the issue might be. The user is just greeted with a mostly-blank page with either 'Scan keyboards' or 'Connect', neither of which do anything (besides 'Connect' throwing a random KeyError in a popup).

I agree with @acron0 in that the program should detect that it was unable to read the serial device, and put up a message accordingly. Alternatively, this should be mentioned on https://www.dygma.com/myraise/.

**Comment by eldelacajita** [comment]
Thanks a lot to the ones that shared the commands here! I agree that, if there's no way around this from the Bazecor side, a clear explanation of what the issue is and which commands to use would be great.

**Comment by enkeys** [comment]
This is a great example of udev guys:

1. In the terminal do ` lsusb | grep Dygma`

The output will be:
```
Bus 001 Device 009: ID YYYY:XXXX Generic Dygma Shortcut Keyboard
```

2. Create a file `/etc/udev/rules.d/50-dygma-raise.rules`

3. Put this line to the file (only replace YYYY and XXXX from first command output)
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="YYYY", ATTRS{idProduct}=="XXXX", GROUP="users", MODE="0666"
```

4. Do `sudo udevadm control --reload-rules `
5. Run Bazecor as usually (user)

And that's it. As a user, you should be able now to see the keyboard inside the Bazecor.

**Comment by ryanerwin** [comment]
@mattvenn 's solution fixed it for me on **Ubuntu**.

```
sudo usermod -a -G dialout $USER
```

Log out, log back in, and run Bazecor again and it works just fine.

As @zalohasa pointed out, under different distros you may have a different user group...

```
ls -la /dev | grep ttyACM0
```

Would be ideal if Bazecor would just test for this, and just tell users which group they should add their user to.

This method is also a bit faster than creating new udev rules...

**Comment by AlexDygma** [comment]
Bazecor since version 0.2.2 alerts you with a message that it doesn't have the right permissions to access the keyboard serial interface, thus we can set this issue as closed.

**Comment by eldelacajita** [comment]
@AlexDygma It would be useful if not only showed that error, but provided a way around it, like the ones shared here. 
Maybe a link to a note on the [MyRaise page](https://www.dygma.com/myraise/)?

**Comment by AlexDygma** [comment]
> @AlexDygma It would be useful if not only showed that error, but provided a way around it, like the ones shared here.
> Maybe a link to a note on the [MyRaise page](https://www.dygma.com/myraise/)?

I'll try to improve this in the next bazecor version instead of leaving it closed, let's see if we can make it clearer for the users.

**Comment by Mailaender** [comment]
> 
> 1. In the terminal do ` lsusb | grep Dygma`
> 
> The output will be:
> 
> ```
> Bus 001 Device 009: ID YYYY:XXXX Generic Dygma Shortcut Keyboard
> ```
> 
> 1. Create a file `/etc/udev/rules.d/50-dygma-raise.rules`
> 2. Put this line to the file (only replace YYYY and XXXX from first command output)
> 
> ```
> SUBSYSTEMS=="usb", ATTRS{idVendor}=="YYYY", ATTRS{idProduct}=="XXXX", GROUP="users", MODE="0666"
> ```

Shouldn't the ID be identical for everyone?

**Comment by AlexDygma** [comment]
as stated in here:
https://stackoverflow.com/questions/47411291/best-practice-for-a-linux-desktop-app-to-ensure-it-has-hardware-access-permissio

This should be the way to go:

https://github.com/JvanKatwijk/qt-dab/issues/34#issuecomment-289270761
https://github.com/EspoTek/Labrador/issues/22#issuecomment-364594369

**Comment by enkeys** [comment]
> > 1. In the terminal do ` lsusb | grep Dygma`
> > 
> > The output will be:
> > ```
> > Bus 001 Device 009: ID YYYY:XXXX Generic Dygma Shortcut Keyboard
> > ```
> > 
> > 
> > 
> > 1. Create a file `/etc/udev/rules.d/50-dygma-raise.rules`
> > 2. Put this line to the file (only replace YYYY and XXXX from first command output)
> > 
> > ```
> > SUBSYSTEMS=="usb", ATTRS{idVendor}=="YYYY", ATTRS{idProduct}=="XXXX", GROUP="users", MODE="0666"
> > ```
> 
> Shouldn't the ID be identical for everyone?

Yes, the ID should be the same (vendor id 1209 as DygmaLab). But you never know why and who will be reading this issue.

> as stated in here:
> https://stackoverflow.com/questions/47411291/best-practice-for-a-linux-desktop-app-to-ensure-it-has-hardware-access-permissio
> 
> This should be the way to go:
> 
> [JvanKatwijk/qt-dab#34 (comment)](https://github.com/JvanKatwijk/qt-dab/issues/34#issuecomment-289270761)
> [EspoTek/Labrador#22 (comment)](https://github.com/EspoTek/Labrador/issues/22#issuecomment-364594369)

That's like what I proposed.

@AlexDygma I created a simple script that can be "feel free to" used in the next releases and included in the readme/installation.

```bash
#!/bin/bash
 
if [ $SUDO_USER ]; then current_user=$SUDO_USER; else current_user=`whoami`; fi
grp=$(groups $current_user)
udev_file="/etc/udev/rules.d/99-dygma-raise.rules"

if ! [[ $grp == *"input"* ]]; then
  echo "WARNING: The current user ($current_user) is not in the 'input' group."
  echo "To add user to this group run as root 'usermod -a -G input $current_user'."
fi

echo "Creating udev rules ..."
cat <<EOF >$udev_file
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", GROUP="input", MODE="0666"
EOF

echo "Reloading udev ..."
udevadm control --reload-rules
udevadm trigger
```

**Comment by nazmulidris** [comment]
I am using Ubuntu 20.04 and just experienced this issue when trying to run the Bazecor AppImage. 

I also use the [UHK keyboard and Agent](https://developerlife.com/2021/03/09/mechanical-keyboard-review/) which automatically creates a `udev` rule in the file `/etc/udev/rules.d/50-uhk60.rules` which makes for a much better UX on Linux. It would be great if Bazecor did the same :+1:. Dygma Raise is an awesome product, and it is a shame to see the new user experience for Linux marred by this permissions issue :cry:.

The comment thread in this issue is somewhat confusing as it shows *two* ways of granting access to the USB device for a non-root user (add `$USER` to the `dailout` group, or create a `udev` rule) :thinking:.

This [support page](https://support.dygma.com/hc/en-us/articles/360016653338-What-to-do-when-Bazecor-says-you-have-insufficient-permission-on-Linux-) also provides a *third* option suggesting that Linux users run the AppImage with `sudo`. However this does not work w/out specifying `--no-sandbox`, eg `sudo ./Bazecor-X.Y.Z.AppImage --no-sandbox` :disappointed:. It would be great if the support page was updated to suggest creating a `udev` rule :+1:.

Here's a fish script that users can run in order to automatically generate the `udev` rule in this file `/etc/udev/rules.d/50-dygma-raise.rules` (when the Dygma keyboard is attached to the computer running this script).

```fish
#!/usr/bin/env fish

# Fish scripting manual: https://developerlife.com/2021/01/19/fish-scripting-manual/

# Run lsusb to get the IDs for the currently attached Dygma keyboard.
set -l idstring (lsusb | grep Dygma | grep -o 'ID.*:[[:alnum:]]*' | sed 's/ID //')
set -l ids (string split ":" $idstring)
set -l XXXX $ids[1]
set -l YYYY $ids[2]
set -l line SUBSYSTEMS=="usb", ATTRS{idVendor}=="$YYYY", ATTRS{idProduct}=="$XXXX", GROUP="users", MODE="0666"

# Generate the rule file.
echo $line > tempfile
sudo mv tempfile /etc/udev/rules.d/50-dygma-raise.rules

# Reload the `udev` rules.
sudo udevadm control --reload-rules
```

**Comment by AlexDygma** [comment]
Just created the PR #193 to solve this issue, it's untested, but should when polished check if the udev rules are created and create them if they are not asking for elevated privileges as required.

if someone wants to give it a shot... 😎

**Comment by nazmulidris** [comment]
@AlexDygma Thanks for getting this PR out so quickly :pray:. I just added a comment to the PR -  https://github.com/Dygmalab/Bazecor/pull/193#pullrequestreview-627582586 suggesting that this script be provided in bash syntax and not fish syntax, since everyone should have bash, but not everyone has fish installed on their Linux distro.

**Comment by nazmulidris** [comment]
@AlexDygma Some updates
1. I translated `installRules.sh` in the [PR](https://github.com/Dygmalab/Bazecor/pull/193#pullrequestreview-628131335) from fish syntax to bash syntax. 
2. I updated the comment [above](https://github.com/Dygmalab/Bazecor/issues/26#issuecomment-808828144) to include this bash shell in addition to the fish shell script.

**Comment by pabrams** [comment]
> > This is not an issue in Bazecor
> 
> It may not be a software problem but it's a UX problem that there is no information. As the OP suggested, the ideal fix would be a prompt. At the very least there should be a note on https://www.dygma.com/myraise/ about this.

Yup, and I still don't see one.  I'll raise another issue, since this one is closed.

**Comment by GazHank** [comment]
> > > This is not an issue in Bazecor
> 
> > 
> 
> > It may not be a software problem but it's a UX problem that there is no information. As the OP suggested, the ideal fix would be a prompt. At the very least there should be a note on https://www.dygma.com/myraise/ about this.
> 
> 
> 
> Yup, and I still don't see one.  I'll raise another issue, since this one is closed.

@pabrams are you able to confirm which distro of Linux you are using, and if you have any udev settings already configured for the raise?

Some small distro don't include udev, so it can be necessary to install udev manually for this to work.

Additionally the initial deployment of udev rules (several releases ago) only enabled access to the raise in "normal" mode, and didn't include rules to allow access in bootloader mode.  Unfortunately the trigger for the pop up only occurs if you are missing access to the keyboard in normal mode.  The easiest way to fix this (I think) is to clear out your existing udev rules for the raise and then rerun bazecor.  The first time it runs (without Sudo) it should trigger the pop up for you to add the udev rules if they don't exist

Ps - I don't know if a reboot is needed after clearing the udev rules...

**Comment by GazHank** [comment]
https://github.com/Dygmalab/Bazecor/pull/211 included the fix for the raise in bootloader mode

**Comment by pabrams** [comment]
I think I already had udev installed because I was messing around with Kmonad for a while.
The auto-udev seemed to work at first, but not during firmware update, and not afterwards, either.  I stopped trying to figure it out, because I'm impatient to configure the thing,  so for now I'm just doing ... (oh shit, where's my backtick...)  ......   `sudo ./B[tab] --no-sandbox`

**Comment by GazHank** [comment]
You could always run `echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="2201", GROUP="users", MODE="0666"\nSUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="2200", GROUP="users", MODE="0666"' > /etc/udev/rules.d/50-dygma.rules && udevadm control --reload-rules && udevadm trigger`

This is what will be configured for any new users, it's just a shame that anyone who used the older version get orphaned with only one of the product codes added

**Comment by VTimofeenko** [comment]
On aforementioned Gentoo if using systemd, the rules for `/dev/ttyACM0` are set in `/lib/udev/rules.d/50-udev-default.rules`:

    25:KERNEL=="tty[A-Z]*[0-9]|ttymxc[0-9]*|pppox[0-9]*|ircomm[0-9]*|noz[0-9]*|rfcomm[0-9]*", GROUP="dialout"

If using the udev rule bundled with Bazecor, it should be set to run after 50, e.g. as `/etc/udev/rules.d/51-dygma.rules`

**Comment by vratojr** [comment]
Hello, to me the problem was still present: when trying to start the application I got:
```  
fusermount: mount failed: Operation not permitted

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```
running with sudo didn't improve things a lot...
In the end I extracted the app with:
```
./Bazecor-1.4.3-x64.AppImage --appimage-extract-and-run
```
then
```
cd squashfs-root
sudo chown root usr/lib/bazecor/chrome-sandbox
sudo chmod 4755 usr/lib/bazecor/chrome-sandbox 
./AppRun
```

And it worked but I had to use the usb cable since through wifi the keyboard wasn't detected.
