### ISSUE TITLE
`LED.NEXT` and `LEG.TOGGLE` icons mixed up

### ISSUE THREAD

**Issue by dj08** [Dygmalab/Bazecor#277]
**Describe the bug**
The icons for `LED.NEXT` and `LED.TOGGLE` seem mixed up.

**To Reproduce**
Notice the `TAP` effect registered when I select what looks like LED toggle switch. The opposite effect is seen for the button that has LED with fast forward icon (which I assume wanted to be the `LED.NEXT` switch).

**Expected behavior**
Expected the function to be the other way, based on what the icons look like.

**Screenshots**
![Screen Shot 2021-09-22 at 11 29 13 AM](https://user-images.githubusercontent.com/17924040/134373861-bdc5087f-c16d-4658-88ca-f39a0bf17ed7.png)

**Desktop (please complete the following information):**
 - macOS 11.6
 - Bazecor Version: Beta10

**Comment by AlexDygma** [comment]
Hey @dj08 @DavidHuizingh !

Thanks to @bryankenote for fixing this issue in his PR, it was merged in beta 12, so enjoy!
