### ISSUE TITLE
iPadOS Globe Key

### ISSUE THREAD

**Issue by dj08** [Dygmalab/Bazecor#278]
**Is your feature request related to a problem? Please describe.**
The iPadOS has the new Globe Key modifier. From some research, it seems it is the same as the standard `Fn` key on some keyboards. I cannot find a way to pick the standard `Fn` key for my keys in Bazecor.

**Describe the solution you'd like**
An option to emulate the `Fn` key, or better still, the Globe Key.

**Comment by alexpargon** [comment]
Any custom apple keys are out of question due to the Copyright and PID VID restriction associated with it, to read more about it, here:

https://gist.github.com/fauxpark/010dcf5d6377c3a71ac98ce37414c6c4
