### ISSUE TITLE
Put project releases in github

### ISSUE THREAD

**Issue by donniebreve** [Dygmalab/Bazecor#28]
**Is your feature request related to a problem? Please describe.**
Currently the download from your website is not working.

**Describe the solution you'd like**
The project releases should also be included here on the github page.

**Describe alternatives you've considered**
Potentially link the Dygma website directly to the github releases page instead of hosting the download, which might encourage people to contribute to the project.

**Additional context**
The Chrysalis releases should probably be deleted.
Dropbox links are scary.

**Comment by algernon** [comment]
I've deleted the chrysalis releases (well, tags) from the Bazecor repo. Will discuss the release plans with @LuisSevilla. We're planning to set up CI/CD, and in-software upgrades, so the releases should be easier - and less scary - to obtain in the not too distant future.

**Comment by donniebreve** [comment]
@algernon and team, thanks for your hard work!
