### ISSUE TITLE
Entering certain special characters in key map breaks render

### ISSUE THREAD

**Issue by DukeFerdinand** [Dygmalab/Bazecor#281]
**Describe the bug**
Entering certain special characters in the key config breaks rendering, requiring a close/open cycle and losing layer work (data loss) as you can't save.

**To Reproduce**
1. Enter app
2. Click any key on a layer (my demo shows layer 3)
3. Searching for any of the following characters causes a render error and shows a blank gray screen

`[`, `]`, `\`, `|`, `?`, `+`, `(`, `)`, `*`

**Expected behavior**
Expected behavior is searching for the character! :)

**Screenshots**

EDIT: Please note that the background lighting selection is not mandatory, it was just out of habit :)

![bazecore-bug](https://user-images.githubusercontent.com/24597186/135108150-9aea0492-072b-4fe5-905b-13e2bf586580.gif)

**Desktop (please complete the following information):**
 - OS: macOS ARM64
 - Bazecor Version: 0.3.3

**Additional context**
I haven't looked at the code, but some of those characters are special characters in JS, so it could be some faulty input validation? It's strange because the object/block opening symbol `{` works as expected

**Comment by AlexDygma** [comment]
Hey @DukeFerdinand !

Thanks for your report! in the beta version we have moved past the search box, it's not longer needed, and as we are very near to closing the initial Beta state, we will probably leave this as it is for the current version, you can try the beta version now if you want!

https://dygma.com/blogs/product-development/new-bazecor-sotware

**Comment by DukeFerdinand** [comment]
@AlexDygma Thanks for clarifying :sunglasses: 

Definitely doesn't need a fix for a pretty small use case if it's not even in the next build! I'll check out the beta :)

**Comment by AlexDygma** [comment]
> @AlexDygma Thanks for clarifying 😎
> 
> Definitely doesn't need a fix for a pretty small use case if it's not even in the next build! I'll check out the beta :)

In fact, if you want to get the latest updates and discuss incoming features with other dygmates, you could pass by our discord! https://discord.gg/ysQfDpkZ here you go 😉
