### ISSUE TITLE
Too many old or unused deps

### ISSUE THREAD

**Issue by pabrams** [Dygmalab/Bazecor#284]
There are a lot of warnings due to deprecated dependencies.  Many of them are not used.  This makes it difficult to work on bazecor, and bloats its footprint. I'm submitting a PR, soon.

**Comment by pabrams** [comment]
Hey @GazHank thanks for the heads up.  
Electron itself is one of the things I tried to update, but rolled that one back.
I'm calling it a day - submitted my PR, for now. Hopefully it's something you guys can merge in to your branches, but let me know if there's anything else I can do to make it easier.  I'll write some more notes over there..

**Comment by pabrams** [comment]
Yes, dependabot is a great idea.

**Comment by AlexDygma** [comment]
Hey @pabrams @GazHank ! 

Thanks for your efforts! in deed we should keep up dependencies, and dependabot is a must in this case, ill look into it to have it set up as soon as I can 😉 

I have been also trying to update the dependencies to reduce the application footprint and improve it's compatibility with newer systems, but it seems it's not enough, as now we have again a problem with linux when detecting the raise.

**Comment by pabrams** [comment]
There might still be some  unused deps, but we can open a separate issue for those. Am closing this one.

**Comment by javierguzman** [comment]
We plan to move to electron forge and make a big update of all libraries so I close this issue
