### ISSUE TITLE
Refactor the USB usage to follow best practice

### ISSUE THREAD

**Issue by GazHank** [Dygmalab/Bazecor#286]
**Is your feature request related to a problem? Please describe.**
BazeCor currently uses 2 packages to interact with USB devices, "USB" for basic scanning and "serialport" for interactions (from updating data to firmware updates).

These packages are invoked within the render process, but electron strongly recommends that the native modules are invoked within the main process and IPC is used to communicate with the render processes.  At present overrides and workarounds are used to keep these working, but electron will probably not support these long term. 

It would also be cleaner to use just one package - I believe only serialport features the breadth of capabilities required for all of the functionality.

**Describe the solution you'd like**
Refactor the serialport scanning, and focus read/write operations to operate via IPC

**Describe alternatives you've considered**
🤔 maybe more workarounds?

**Additional context**

https://www.electronjs.org/docs/api/ipc-main

**Comment by pabrams** [comment]
I might tackle it.  I'll post here again if I decide to.

**Comment by GazHank** [comment]
This should be a little easier since the updates to serialport V10+ and the switch to NAPI, but I've still not found time to look at refactoring this.  I'll try to find time for this, as I also think it should make module swaps or replacements easier in the future if all of the logic was stripped out of the renderer
