### ISSUE TITLE
Comodo Firewall with HIPS will trigger Bazecor to lockup/freeze your computer

### ISSUE THREAD

**Issue by sakeperez** [Dygmalab/Bazecor#295]
**Describe the bug**
If your computer (windows10) is running comodo firewall with HIPS enabled and you run any version of Bazecor the computer will lockup.

**To Reproduce**
1. Install comodo firewall (free edition) with default features enabled
2. Run Bazecor
3. You will get warning of each application Bazecor tries to run. Allow each action. At some point it looks like Bazecor is trying to execute itself. If you allow it, the computer will very quickly slow and freeze. Only a reboot will fix it. 

Simply choosing "Allow" and "remember my selection" does not fix the issue. Only fix is to create a custom rule for Bazecor:
1) It must allow all actions. 
2) For the run executable action you must add an exclusion to allow access to:
c:\Users\<username>\AppData\Local\Programs\BAZECOR\*

**Expected behavior**
Bazecor shouldn't freeze the computer with default comodo options. 

**Desktop (please complete the following information):**
 - OS: Windows10
 - Bazecor Version: 1.0.0beta11 also tested 1.0.0beta10 and 0.3.3 with same result

**Comment by GazHank** [comment]
Do you fancy the same issues with other electron apps?  (Such as VScode?) Do you face this issue with other apps that are not signed?

0.3.3 doesn't as far as I recall include any external internet requests (everything in local after the install); so I would be inclined to think that the issue is with the "firewall" rather than Bazecor; as it seems to be interfering with an application that isn't even trying to use the internet.

**Comment by sakeperez** [comment]
I use VSCode and other electron apps without issues, no special configurations.

Comodo is primarily a firewall, but the HIPS component monitors file access and what other .exe an application may try to launch. The odd behavior is that the notification says that Bazecore.exe is trying to launch Bazecore.exe. If I click "Allow" it appears like it gets into an infinite loop of launching itself until all resources are exhausted. If I add the exclusions as noted everything works without issue.

**Comment by GazHank** [comment]
I wonder if the electron packager we use needs to be reconfigured, or updated.  I still find it far nicer to build locally rather than use the packaged build; of course that isn't ideal for everyone

**Comment by AlexDygma** [comment]
Hey @sakeperez, @GazHank ( long time no see 😉) !

I will have to check this locally to find the reason, but we may have to talk with Comodo to check this out with them

**Comment by javierguzman** [comment]
Closed as it is stale
