### ISSUE TITLE
Superkey editor incorrectly stores tap & hold

### ISSUE THREAD

**Issue by lenart** [Dygmalab/Bazecor#296]
**Describe the bug**
No matter which event (besides Tap) I choose the key combo is assigned to Hold. See screenshot.

**To Reproduce**
1. Go to 'Superkey editor' and create a new superkey
2. Assign V as the Tap
3. Assign OS + V as the Tap & Hold
4. Save superkey
5. In Layout editor assign the superkey to any key (it works as V for Tap and OS + V for Hold)

**Expected behavior**
It should reflect the settings used when creating the superkey

**Screenshots**

![CleanShot 2021-11-17 at 21 08 47](https://user-images.githubusercontent.com/9228/142275207-a21af6c6-07e5-490d-968c-1e8ad61d06d0.gif)

**Desktop (please complete the following information):**
 - OS: Mac
 - Bazecor Version: 1.0.0beta11

**Additional context**

I've tried creating several keys, deleting all existing superkeys without success. Using different events (eg. Double tap) also stores combinations as Hold.

**EDIT:** I'm thinking that it's not possible to have a superkey without a Hold option. If I add more events, they seem to be stored correctly.

What I wanted to do is to assign a combination (let's say cmd+alt+v to open clipboard history) to the V key. If I have a superkey set on V, pressing CMD+v quickly, just outputs the v character without correctly recognizing that it was hit with CMD modifier. If I press the CMD, hold it for few ms and then press V it works as expected.

**Comment by AlexDygma** [comment]
Hey @lenart !

This should be solved for you on beta 12! check it out just to be sure!
