### ISSUE TITLE
Number Pad's "Enter" Text

### ISSUE THREAD

**Issue by DavidHuizingh** [Dygmalab/Bazecor#298]
**Describe the bug**
The lower keyboard selector displays the text "Intro" and the applied text on the Dygma Raise keyboard displays "Num Enter".

**To Reproduce**
1. Navigate to Layout Editor
2. Select key on upper keyboard
3. Click lower keyboard's "Intro" key

**Expected behavior**
I expect both keyboard graphics to communicate the same/similar messages. I don't know what "Intro" means, and I probably should read "Enter" or match the other non number pad enter graphic:
![image](https://user-images.githubusercontent.com/19331250/142662348-ff7ece3c-a852-4a21-b2a8-ffc7b0c05fe1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/19331250/142661776-50126f62-6cef-4554-970e-396dd00d25fb.png)

**Desktop (please complete the following information):**
 - OS: WIndows Build 19043.1237
 - Bazecor Version: 1.0.0-beta11

**Comment by AlexDygma** [comment]
Hey @DavidHuizingh !

You're right this should be changed to the corresponding icon to be language agnostic. i will change it for the upcoming beta!
