### ISSUE TITLE
Cannot Scroll in "Preferences"

### ISSUE THREAD

**Issue by DavidHuizingh** [Dygmalab/Bazecor#299]
**Describe the bug**
In "preferences" I cannot see or select all the options available.

**To Reproduce**
1. Open app
2. Connect to keyboard
3. Select "Preferences" (the bottom option on vertical toolbar)
4. Look for "Mouse Keys" options set (it's not visible)

**Expected behavior**
I am able to navigate to all the options available in preferences.

**Screenshots**
Without resizing the window:
![image](https://user-images.githubusercontent.com/19331250/142663495-41c46f85-5bb2-458f-90df-01eecece63db.png)

App "Fullscreened" on a 1920x1080 monitor:
(notice not all options in "advanced" are visible)
![image](https://user-images.githubusercontent.com/19331250/142663624-15e3ecc9-eb3c-42bb-b3c8-c03cc229a3f6.png)

App "Fullscreened" on 2440x1440 monitor:
(now everything is visible)
![image](https://user-images.githubusercontent.com/19331250/142663900-dc29c268-f812-4216-aaee-fc09c319179f.png)

**Desktop (please complete the following information):**
 - OS:  Windows Build 19043.1237
 - Bazecor Version: 1.0.0-beta11

**Additional context**
Its nice that settings attempt to arrange themselves to best suite the display, but since that won't prevent common screen sizes I wonder if simply adding a scrollbar would be a quick & easy solution.

**Comment by AlexDygma** [comment]
Hey @DavidHuizingh !

The bug has been solved in beta 12, enjoy!
