### ISSUE TITLE
Shift to layer key can not go back

### ISSUE THREAD

**Issue by ohxyz** [Dygmalab/Bazecor#306]
**Describe the bug**
A key is assigned to `Shift to layer 1` on layer 0. When the same key is assigned to `Shift to layer 0` on layer 1, it does not work. However, if the key is assigned to `Shift to layer X` on layer 1, e.g. `2`, other than `0`. It works.

**Expected behavior**
As described above, when I press the key to shift back to layer 0, it can work.

**Desktop**
 - OS: Windows
 - Bazecor Version: 0.3.3

**Comment by javierguzman** [comment]
Hello! Does this still happen to you? I guess new versions are ok right?
