### ISSUE TITLE
Layer overlay for quick reference

### ISSUE THREAD

**Issue by shadeMe** [Dygmalab/Bazecor#307]
**Is your feature request related to a problem? Please describe.**
For beginners of the Raise, it would be very useful to have the keyboard layout/layers at the ready for quick reference. Currently, the only way to do this would be to print out the layers ahead of time on a piece of paper and have it on your desk.

**Describe the solution you'd like**
Instead of having a physical printout, it would be an useful alternative to have a shortcut that you can map in Bazecor that displays a fullscreen overlay of the currently loaded layers. Similar to [this](https://docs.microsoft.com/en-us/windows/powertoys/shortcut-guide).

**Comment by shadeMe** [comment]
Here's an example of what I have in mind - https://old.reddit.com/r/DygmaLab/comments/rwhnsa/quickly_view_your_keymap_on_x11_though_it/

**Comment by AlexDygma** [comment]
Hey @shadeMe !

This is a great idea! ill look into how can we implement this in a way that it works in Win, Mac & Linux.

**Comment by pabrams** [comment]
You can do it if you have electron loaded, but if it's a requirement that electron not be loaded, each platform's solution will be different, I think.

**Comment by javierguzman** [comment]
I close this because it is already under our radar to do this type of overlay with a system tray, etc.
