### ISSUE TITLE
Non-modal flashing UI

### ISSUE THREAD

**Issue by shadeMe** [Dygmalab/Bazecor#308]
**Describe the bug**
The UI view that is used to flash new firmware is non-modal, i.e., even after the firmware update process has started, the user is able to break the UI flow by switching to a different view.

**To Reproduce**
1. Click on the 'Firmware Update' button on the sidebar.
2. Start the update process.
3. Whilst the firmware is being flashed, switch to another view by clicking on any other button the sidebar.
4. Switch back to the Firmware Update view.
5. The view will be reset to its initial state, allowing the user to begin another flashing operation (potentially before the previous one has ended).

**Expected behavior**
The app should disable all user interactions during the flashing process.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 1.0.0beta 13

**Comment by AlexDygma** [comment]
Hey @shadeMe !

You are totally right, we will disable the rest of the interactions with the application until the flashing procedure has ended or has been cancelled with the proper button.

Thanks for the head's up! 👍

**Comment by AlexDygma** [comment]
This is now fixed on the latest beta version!
