### ISSUE TITLE
Saving Layers fails under strangely specific conditions

### ISSUE THREAD

**Issue by elkowar** [Dygmalab/Bazecor#31]
# The Bug
I've found a very strange bug that can happen when configuring secondary layers

 
# Reproducing the Error
My current setup is:
layer 0: a mildly modified version of the default german Layer 0
Layer 1: a mildly modified version of the default Layer 1
Layer 2: a Layer with some navigation and special characters

When setting one of the Thumb-keys in Layer 0 to `xxx` whilst having set the key to transparent in Layer 1, as soon as I try to store that configuration, the keyboard suddenly disconnects and then reconnects, with the changes lost.
I was not yet able to fully understand when this happens, but it currently seems as tough it 
- only happens with the Thumb-keys
- isn't strictly about layer 1: when not having ever changed the transparent-config of layer 1, I was first having the problem with Layer 2: as soon as I set the thumb-key to something other than transparent in layer 2, I was unable to set it back to transparent as long as I didn't change the key's config on Layer 0 to be non-`xxx` 

**Expected behavior**
`xxx`-configuration should work with `transparent`, there should not be a keyboard disconnect when trying to save.

# Screenshots & log
## Log for an attempt to do said configuration 
[-1579249141649.log](https://github.com/Dygmalab/Bazecor/files/4075696/-1579249141649.log)

## Layer 0, with `xxx` on thumb-key 
(works as long as the key is not `transparent` on Layer 1)
![image](https://user-images.githubusercontent.com/5300871/72595652-975afc00-390a-11ea-9579-40563a706bef.png)

## Layer 1 
(as soon as i change the `<` on the thumb-key to `transparent` and try to save, the keyboard disconnects shortly, resetting the config to the last saved)
![image](https://user-images.githubusercontent.com/5300871/72595732-ca04f480-390a-11ea-8caa-ffcfa9d709b9.png)

# OS Info
 - OS: Windows 10
 - Bazecor Version: 0.1.0

**Comment by algernon** [comment]
Can you open the developer console (`Ctrl+Shift+I`) before saving the layout, reproduce the problem, and see if there are any errors present there?

**Comment by XamiKami** [comment]
there are no errors in the developer-console for me

**Comment by bagukiri** [comment]
Hello I have the same issue and here's my developer console log.

It happens when I try changing a color on a key on layer1 (or any layer for that matter).  Changing the keybinding still works.

![image](https://user-images.githubusercontent.com/618550/72923837-aa077380-3d04-11ea-9c2b-aba3f4a6b8bd.png)

**Comment by bagukiri** [comment]
Found a workaround.  Duplicating layer1 to a different layer and overwriting the original seems to restore my functionality.

**Comment by alexvy86** [comment]
I just ran into a very similar problem. I tried narrowing the setup that causes it, and so far what I have found is that if I try to set my right-side bottom-most thumb keys to Right Ctrl and Right Alt on Layer 0, and set both of them to Transparent on Layer 1, when I try to save the configuration then the saving icon keeps spinning indefinitely and the keyboard stops working altogether. The dev tools console shows a couple of logged messages, and eventually a "Communication timeout" error:

<img width="428" alt="developer tools log" src="https://user-images.githubusercontent.com/716334/92072407-c8dbe700-ed76-11ea-8f67-a2f04c9e64f6.png">

Here's a gif demonstrating the issue:

![bazecor-cant-save-changes](https://user-images.githubusercontent.com/716334/92072386-bf527f00-ed76-11ea-94c8-1e9c07610090.gif)

For now my workaround is to set one of those two keys explicitly to the same key that Layer 0 has, but I don't see why setting them both to transparent should cause an issue.

**Comment by alexvy86** [comment]
I just tried restarting the computer with the Raise unplugged, like the workaround [here](https://github.com/Dygmalab/Bazecor/issues/72) suggests, but it didn't help.

**Comment by alexvy86** [comment]
I've managed to reproduce this at will with a specific change to one of my layers. Most of the keys in that layer are black (code 11). If I change any key to one of the first 10 colors in Bazecor (so any single-digit code, 0-9) then trying to save those changes hangs.

Here are some logs from Bazecor's developer console for several attempts. In the failure cases, only 4 `focus.request` messages are logged, and then Bazecor hangs (and the keyboard becomes completely unresponsive until I disconnect and reconnect it). With a diff-app I can see that the only difference in that message is the 1vs2-digit color code (see screnshot below).

[color 11 - success](https://github.com/Dygmalab/Bazecor/files/5192254/color.11.-1599617397892.log)
[color 10 - success](https://github.com/Dygmalab/Bazecor/files/5192258/color10.-1599618024567.log)
[color 3 - failure](https://github.com/Dygmalab/Bazecor/files/5192255/color.3.-1599617448148.log)
[color 0 - failure](https://github.com/Dygmalab/Bazecor/files/5192256/color.0.-1599617773726.log)
[color 9 - failure](https://github.com/Dygmalab/Bazecor/files/5192257/color.9.-1599617973997.log)

![image](https://user-images.githubusercontent.com/716334/92547358-52c5fd00-f21a-11ea-9037-680fc32fb9e5.png)

**Comment by AlexDygma** [comment]
Hello @alexvy86 

I'm trying to reproduce your issue and im not able to, can you please check if with the newer version of [Bazecor v0.2.4](https://github.com/Dygmalab/Bazecor/releases/tag/bazecor-0.2.4) do you still have the same problem?

Thanks in advance!

**Comment by alexvy86** [comment]
I just saw the new release earlier today, I'll try again after I download it and update this issue.

**Comment by alexvy86** [comment]
I can confirm neither of my issues happen anymore with Bazecor v0.2.4 😃. I can set several of my T# keys to transparent instead of hardcode the same configuration as the layer below (issue 1) and apply colors correctly to the keys in the all-black layer that I used for issue 2. Thanks @AlexDygma !

**Comment by AlexDygma** [comment]
> I can confirm neither of my issues happen anymore with Bazecor v0.2.4 😃. I can set several of my T# keys to transparent instead of hardcode the same configuration as the layer below (issue 1) and apply colors correctly to the keys in the all-black layer that I used for issue 2. Thanks @AlexDygma !

Glad it works for you! 😄
