### ISSUE TITLE
Can't update Dygma from 0.3.3 to 0.3.4 under Mac

### ISSUE THREAD

**Issue by skaurus** [Dygmalab/Bazecor#313]
**Describe the bug**
I can see in Bazecor that my firmware version is 0.3.3 and that 0.3.4 is available. I can flash my keyboard successfully, but then Bazecor reports my firmware version as still 0.3.3

**To Reproduce**
See above

**Expected behavior**
Firmware really updates and Bazecor reports the latest version

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Bazecor Version: 0.3.4

**Comment by AlexDygma** [comment]
Hey @skaurus !

Sorry for the late response, but this was an issue with the distribution of that FW, we didn't update the version number correctly, but the changes were there.

Hope it's helpful!
