### ISSUE TITLE
Offer an easy access to the Edit/create Macros feature

### ISSUE THREAD

**Issue by shining-cat** [Dygmalab/Bazecor#316]
**Is your feature request related to a problem? Please describe.**
I'm trying to polish some macros, but I always have to reach the layer they're affected to, and click the concerned key to access the edit macros screen. Same for creating one, I can't find a way to access the macros feature without coming in from affecting one to a key.

**Describe the solution you'd like**
I would like an easy access to the macros administration feature, and to be able to add or edit them without finding the bound key.
This might be in the general menu on the left, or a button on the top right (although it's not really related to layers admin)

**Describe alternatives you've considered**
I have to select the layer where I have any macro, then any key with one bound. Then only can I click on the Edit macros button and modify any of them.
I can also select an unbound key (otherwise it would override the binding present at the moment) and through the Key config panel, choose create macro, then I reach the screen at last. But this is even more cumbersome.

**Additional context**
Granted, configuring macros is not something one might want to do everyday, but when one's trying to polish them, then, actually, an easy access is sorely missed ;)

**Comment by AlexDygma** [comment]
This has been changed in the Beta version of Bazecor! I suggest you try beta 14 which is bound to be released very soon, it has a major UI overhaul and a specific screen to modify and create new macros.

Please give us your thoughts about the new interface here! 🤗

**Comment by javierguzman** [comment]
Close as no feedback/interaction happened after Alex's response
