### ISSUE TITLE
Uncaught Exception: object destroyed at `NativeTheme.theThemeHasChanged`

### ISSUE THREAD

**Issue by iansimonson** [Dygmalab/Bazecor#318]
**Describe the bug**
The following popup occurs once in a while. The main window also closes though the application stays open (mac). It seems to usually happen when I wake my laptop from sleep if bazecor remained open.

```js
Uncaught Exception:
TypeError: Object has been destroyed
at NativeTheme.theThemeHasChanged (/Applications/Bazecor.app/Contents/Resources/app.asar/webpack:/src/main/index.js:93:12)
at NativeTheme.emit (events.js:315:20)
```

If I had to guess it's occurring when I put my laptop to sleep at night and wake in the morning as the system theme changes from dark to light.

**To Reproduce**
Unknown, it's intermittent. If guess above is correct then keep bazecor open while system theme changes.

**Expected behavior**
Window should change theme with system. Exception should be caught/handled.

**Screenshots**
<img width="263" alt="Screen Shot 2022-02-20 at 6 50 02 AM" src="https://user-images.githubusercontent.com/10237796/154848661-15401e53-ebf9-4a19-869f-8e72530664f1.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Bazecor Version: Version 1.0.0-beta13 (1.0.0-beta13)

**Additional context**

**Comment by AlexDygma** [comment]
We will take a look into it @iansimonson ! it should be solved as soon as we can
