### ISSUE TITLE
"Macro Name" gets erased after closing Bazecor

### ISSUE THREAD

**Issue by sandypockets** [Dygmalab/Bazecor#329]
**Describe the bug**
I created some macros in the Macro Editor, and named each of them. However after closing Bazecor (fully quitting it), and reopening it, the names have reverted back to their numerical IDs (0, 1, 2, 3, etc). 

That said, it sounds like some work in the Macro Editor is already underway (as suggested in #163), so this might already be on your radar.

**To Reproduce**
1. Open Bazecor, and navigate to the Macro Editor
2. Create a macro, and give it a custom name
3. Save the macros to the Raise
4. Close Bazecor
5. Reopen Bazecor, and navigate to Macro Editor. 
6. Note the macro name has reverted to an ID

**Expected behavior**
The macro name will not revert to the ID, and the given name will persist. 

**Screenshots**

<img width="1894" alt="Screen Shot 2022-04-15 at 9 20 28 PM" src="https://user-images.githubusercontent.com/41454557/163656315-832b8074-9873-4fae-940d-489cb93faa6d.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1 (Intel)
 - Bazecor Version: 1.0.0-beta13

**Additional context**
- The Macros are in use on Layers 1, and 2, but not on layer 0. 
- It only started happening _after_ adding my own custom Macros. Until then, the default "Hey Dygmate" macro continued to remain.

**Comment by AlexDygma** [comment]
Hey there @sandypockets !

the new beta version we are going to release solves this issue, or so it should do, check it out and tell us if this is solved for you!

**Comment by sandypockets** [comment]
Thanks @AlexDygma! I just upgraded to `Version 0.3.3 (0.3.3.271)` and it seems all my macros have been deleted. Luckily I only had a handful of them, so it's not a big deal.

I noticed the export option's tooltip in the new Bazecor mentions macros are excluded.  Is there a way to back up the macros that I am missing? 

<img width="745" alt="Screen Shot 2022-04-26 at 8 54 49 PM" src="https://user-images.githubusercontent.com/41454557/165416823-f84a7dbb-edce-4fa2-a049-635f1c08a5d1.png">

Other than this, really liking the updated Bazecor, nice work and big thanks to you and the team!

**Comment by AlexDygma** [comment]
> Thanks @AlexDygma! I just upgraded to `Version 0.3.3 (0.3.3.271)` and it seems all my macros have been deleted. Luckily I only had a handful of them, so it's not a big deal.
> 
> I noticed the export option's tooltip in the new Bazecor mentions macros are excluded. Is there a way to back up the macros that I am missing?
> 
> <img alt="Screen Shot 2022-04-26 at 8 54 49 PM" width="745" src="https://user-images.githubusercontent.com/41454557/165416823-f84a7dbb-edce-4fa2-a049-635f1c08a5d1.png">
> 
> Other than this, really liking the updated Bazecor, nice work and big thanks to you and the team!

You're welcome @sandypockets ! I'm glad you are enjoying the release 😉 

The way to backup macros is with their editor screen, go to a macro assigned key, click below in edit macro, and then look at the options at the bottom of the modal window.

![image](https://user-images.githubusercontent.com/70891884/165473362-5228f640-c8dd-4e91-a458-22fc9c83bed7.png)

As you can see at the bottom left, you have specific import-export buttons for the macros, on the beta, this is done automatically every time you save any change, so backups stop being an issue for the user.

**Comment by javierguzman** [comment]
This is now solved so I close the issue.
