### ISSUE TITLE
Multiple functions mapped to a key with use of a Raise specific function key

### ISSUE THREAD

**Issue by ekakela** [Dygmalab/Bazecor#34]
**Is your feature request related to a problem? Please describe.**
When mapping keys to raise specific functions (ie lock to layer 1), you cannot do it with modifier.

I would like to utilize either "System" or Control as a modifier inside the keyboard with numbers to move between layóuts since there is no next and previous layout options.

**Describe the solution you'd like**
Create (or use the existing system modifier that is planned to be removed) as a "Raise specific" modifier and allow mapping multiple options to single key (with modifier, without modifier) 

ie button "1" without the modifier would still be number 1 and with the System modifier could be "Lock to layer 1" and same for other layers. 

**Describe alternatives you've considered**
Other maybe faster to do alternative would be to implement options to have next and previous layer keys binded to keyboards but I see that having possibility to map multiple meanings into one button, with modifiers would be the best option 

**Additional context**
N/A, happy to answer any further questions

**Comment by ekakela** [comment]
Currently one way to circumvent this is to waste one layer to lock layer buttons and use one key as switch to that layer in every layer...

**Comment by algernon** [comment]
The firmware does support prev/next layers, so exposing that functionality through Bazecor is fairly easy, I've added that part to the [roadmap](https://trello.com/c/7OhBcDk3/126-expose-the-next-prev-layer-keys-in-bazecor) (don't mind where it is on the column, the order there is not strictly adhered to, and changes all the time).

Using a layer key like a modifier is a neat idea, too, shouldn't be too hard to implement either. Once the firmware side of that is done, letting Bazecor set up keys like that is easy. The firmware side of it is a bit more complicated, but not terribly. Mind you, that'll only allow you to switch to layers 0-9, but that should be plenty.

**Comment by algernon** [comment]
The firmware side now has a PR in keyboardio/Kaleidoscope#805.

**Comment by javierguzman** [comment]
I think this is covered by super keys, please, reopen if they don't solve your problem
