### ISSUE TITLE
Are all these issues for the Development version, or the Production version? Or is it a combination of both?

### ISSUE THREAD

**Issue by pabrams** [Dygmalab/Bazecor#341]
I get the sense that this list of issues may include issues identified against basically any version of Bazecor, including Development (Beta?) and "Stable" versions, but that for the most part, we don't know which. 
Is that accurate? 

In other words: 
What should I be doing if I find issues with the latest build of the dev branch (last commit 223d88cdce07c88f5444e69f0471fb219e7cfcdc)?    Do I post here?

**Comment by pabrams** [comment]
Reason I ask, is that a large swathe of functionality seems completely broken, for me. I can't seem to set any superkeys, for example.. The dropdown  for "Select Superkey" is empty, and if I try to use the four drolpdowns on the right, 
![image](https://user-images.githubusercontent.com/1376688/167745640-03b89410-1d9b-469b-b568-884a4865a61b.png)
I find that choosing a value for any one of these clears all the other values, which doesn't seem like the intended behaviour...

**Comment by pabrams** [comment]
commit 223d88cdce07c88f5444e69f0471fb219e7cfcdc

**Comment by MattSturgeon** [comment]
> I get the sense that this list of issues may include issues identified against basically any version of Bazecor, including Development (Beta?) and "Stable" versions, but that for the most part, we don't know which. Is that accurate?


Yes that is generally how Github issues works. In an ideal world, issues would only be reported against the latest development version, because an issue on the latest stable release may have already been fixed. It's also good if issues state which version/commit the bug can be reproduced on. If that's missing from an issue then it's anyone's guess.

> In other words: What should I be doing if I find issues with the latest build of the dev branch (last commit [223d88c](https://github.com/Dygmalab/Bazecor/commit/223d88cdce07c88f5444e69f0471fb219e7cfcdc))? Do I post here?

Yes.

**Comment by javierguzman** [comment]
Hello @pabrams ! I believe you have been answered already! I must say that I am trying to clean the repository as there are a lot of issues that are old and not applicable anymore. I would really like to have a healthy repo. If you find something you do not like or a bug, by all means, please open an issue here or contact our support.
