### ISSUE TITLE
Keyboard Selection with multiple Neurons broken

### ISSUE THREAD

**Issue by MuMuQ** [Dygmalab/Bazecor#342]
**Describe the bug**
The keyboard selection list uses the name of the first Neuron in the Neuron Manager's entries as for all selection entries and only the first entry can be selected.

**To Reproduce**
1. Connect only the first Raise
2. Start Bazecor and name the first Neuron
3. Disconnect the first Raise
4. Connect only the second Raise
5. Restart Bazecor and name the second Neuron
6. Connect both Raise/Neurons at the same time
7. Restart Bazecor, for good measure
8. Open "Select keyboard" dropdown
9. BONUS: Try to select the second Neuron

**Expected behavior**
Each Neuron is listed by the name assigned in the Neuron manager and when clicking on the second entry in the list, the second Neuron is selected and can be connected to.

**Screenshots**
![image](https://user-images.githubusercontent.com/10376200/167929071-710e6c86-aa7b-42a1-9cad-9f92231e59f6.png)
![image](https://user-images.githubusercontent.com/10376200/167929006-23231b22-ba86-4325-a46b-ff369f6a877e.png)

Logfile:
[-1652297227377.log](https://github.com/Dygmalab/Bazecor/files/8672866/-1652297227377.log)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Bazecor Version: 1.0.0 Beta 14

**Additional context**
I previously had a third Neuron Entry in my Neuron Manager which had another name and was placed as the first entry in the Neuron manager list and the Black and White Neuron were then displayed with the name of this additional entry so I am very sure that the first entry's name is used. After removing that entry, it switched to the new first Neuron in the list.

EDIT: Even with only the second Neuron connected, the name of the first Neuron is displayed in the keyboard selection.

**Comment by javierguzman** [comment]
This is done right @AlexDygma ?

**Comment by AlexDygma** [comment]
Yes, @javierguzman , This is solved and it's going to be totally reworked, so we can close this issue :)
