### ISSUE TITLE
Sleep / soft-power-off key

### ISSUE THREAD

**Issue by sirdodger** [Dygmalab/Bazecor#343]
**Is your feature request related to a problem? Please describe.**

I would like to be able to put my computer to sleep, like the dedicated sleep keys on mass-produced keyboards do.

**Describe the solution you'd like**

Assign a soft-power/sleep key (scan code [e05f](https://en.wikipedia.org/wiki/Power_key)).  Alternately, allow any custom hex scan code to be assigned to a key.

**Describe alternatives you've considered**

I currently use a macro to solve the problem, but it is inelegant, prone to failure, and needs specific preconditions such as having the desktop have keyboard input focus.

**Comment by Lite5h4dow** [comment]
literally just thought of this rn
im gonna see if i can add the keys

**Comment by ckjeldmann** [comment]
What macro do you use? I've se mine up the following way - it works most of the time.

![billede_2022-06-07_221201681](https://user-images.githubusercontent.com/106890075/172473496-57087dc0-1a1d-4ef4-9ffa-488147333acb.png)

**Comment by ckjeldmann** [comment]
Maybe something like this would work better for you?

![billede_2022-06-09_224842146](https://user-images.githubusercontent.com/106890075/172941745-b80b9f4c-7874-44b3-a5df-562904426d03.png)

**Comment by Lite5h4dow** [comment]
found the key that you need in kaleidoscope: https://github.com/keyboardio/Kaleidoscope/blob/master/src/kaleidoscope/key_defs/sysctl.h
line:21
just need to add it to bazecor

**Comment by Lite5h4dow** [comment]
made a PR for the shutdown button and the sleep button. do be warned however, there is no confirmation, it acts like the powerbutton on a laptop keyboard. putting your machine to sleep / off instantly. so make sure its not in a place that would be accidentally hit.

**Comment by ckjeldmann** [comment]
That's awesome!

But how do I use it? Can someone guide the n00b? 🤣

**Comment by Lite5h4dow** [comment]
> That's awesome!
> 
> But how do I use it? Can someone guide the n00b? 🤣

You can either build the development branch yourself or wait for the next release 😜

**Comment by Lite5h4dow** [comment]
> Good things come to those who wait, right? ;-)
> 
> I use hibernate, rarely shut down and never sleep. Was that option added as well or was it left out?

Hibernate isn't an option but it does appear to hybernate on windows although nowadays the difference between hybernate and sleep is where the system state is stored so I don't think it makes too much difference
