### ISSUE TITLE
Bug Nordic layout - UI key positions vs reality

### ISSUE THREAD

**Issue by ckjeldmann** [Dygmalab/Bazecor#346]
**Describe the bug**
Explained in the picture

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: Bazecor 1.0.0 Beta 14 

![bazecor bug](https://user-images.githubusercontent.com/106890075/172028144-493e35d2-1ba2-4362-88a3-6b6aaf26f118.png)

**Comment by AlexDygma** [comment]
Solved on beta 15!
