### ISSUE TITLE
Add Eject key at Mac

### ISSUE THREAD

**Issue by Riki2576** [Dygmalab/Bazecor#35]
How can I add the eject key of the mac keyboard to one key?

**Comment by algernon** [comment]
Unfortunately, I do not have a mac keyboard, so can't check myself what keycode the eject key generates. If someone could tell me what's the keycode, or even better, what's the USB HID code for the Eject key, that'd be great.

I can guess, but that's not the best experience, I think :)

**Comment by Riki2576** [comment]
If you tell me how to do I can help with that.
Actually I use Karabiner for remap another key and use it as an eject key
