### ISSUE TITLE
[Feature] Change LED glow slider

### ISSUE THREAD

**Issue by mortenlerudjordet** [Dygmalab/Bazecor#36]
**Is your feature request related to a problem? Please describe.**
Excuse me if this has already been addressed, though it would be nice to have a slider that changes the glow intensity of the LEDs in software if possible.

**Describe the solution you'd like**
A slider that sets the glow intensity of the LED both for keys and underglow.

**Comment by algernon** [comment]
Something like this?

![Screenshot from 2020-01-23 13-56-32](https://user-images.githubusercontent.com/17243/72986311-376fc400-3de8-11ea-8e12-6492beb68d2f.png)

That's already implemented, and will be part of the next release due very soon.

**Comment by mortenlerudjordet** [comment]
Sweet, I'll close this then.
