### ISSUE TITLE
Cannot flash new firmware

### ISSUE THREAD

**Issue by Lite5h4dow** [Dygmalab/Bazecor#363]
**Describe the bug**
I cannot complete the flashing process in the latest beta
**To Reproduce**
1. connect to keyboard
2. go to firmware update
3. start flashing process
4. press button
5. release button
6. stopped...

**Expected behavior**
flashing should complete

**Screenshots**
![image](https://user-images.githubusercontent.com/18059545/184505620-fc2455b0-c776-46cb-8172-4ecfd1fa029d.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Bazecor Version: 1.0.0 beta15

**Additional context**
ive tried both as admin and not as admin and in different usb ports...

**Comment by lytefast** [comment]
Ran into the same issue when upgrading from FW 0.3.4. The prompt is wrong. Keep holding the esc key down past step 3.

**Comment by Lite5h4dow** [comment]
no dice, 
tried holding the key down but didn't get anything

**Comment by AlexDygma** [comment]
The whole flashing process has been refactored and now it's much more stable and clean, this issue should no longer be present.

**Comment by Elsie19** [comment]
https://github.com/Dygmalab/Bazecor/assets/58742515/46cca972-a3a3-4360-8cb6-17473c78c184

I have the same issue.
