### ISSUE TITLE
1.0.0b15: Saving the 98th macro deletes all macros

### ISSUE THREAD

**Issue by SinH4** [Dygmalab/Bazecor#365]
I have exactly the same issue as described in issue 292 with 1.0.0-beta15, except that for me it happens when saving the 98th macro instead of the 17th, despite Bazecor telling me that the macro memory is only 47.4% full.

Behavior and reproduction is exactly as described in issue 292, except replace the number 17 with 98. I know 98 is a lot of macros, but then again the memory appears to be far from full at this point.

Bazecor Version: 1.0.0b15
OS: happens on both Debian 11 and an up-to-date Arch Linux system

_Originally posted by @SinH4 in https://github.com/Dygmalab/Bazecor/issues/292#issuecomment-1218424187_

**Comment by alexpargon** [comment]
This is solved in recent versions!
