### ISSUE TITLE
can no longer map multiple modifier key

### ISSUE THREAD

**Issue by yangkennyk** [Dygmalab/Bazecor#368]
**Describe the bug**
After updating to the latest bazecor and firmware I can no longer map multiple modifier keys

**To Reproduce**
1. Map a key to a modifier key (ctrl,alt,etc)
2. The "add a modifier" section is no longer clickable.

**Expected behavior**
The "add a modifier" section should be clickable so users can map meh/hyper keys etc. Previous modifiers I had prior to updating still work though. 

**Screenshots**
cannot add more modifiers
![image](https://user-images.githubusercontent.com/6680040/188317179-efaeb26b-8de6-407c-b4f8-d7444b894b6b.png)

previous modifiers still functioning
![image](https://user-images.githubusercontent.com/6680040/188317211-3898c5ab-d7e2-4ade-b316-542383d3ed91.png)

**Desktop (please complete the following information):**
 - Mac Monterey 12.5.1
 - Bazecor Version: Bazecor 1.0.0 Beta 15 with v1.0.9 beta firmware

**Comment by lehenric** [comment]
Having same issue, current workaround is using Bazecor Beta 14.

**Comment by javierguzman** [comment]
I have not been able to reproduce this error so I guess it was just an old Bazecor problem. Please, feel free to reopen if the problem persists on your end after upgrading.
