### ISSUE TITLE
Support Korean keyboard layout

### ISSUE THREAD

**Issue by TaeksuKim** [Dygmalab/Bazecor#380]
**Is your feature request related to a problem? Please describe.**
Korean keyboard layout is exactly same with English ANSI's one except just two extra keys:
- `LANGUAGE1` (0x90 = 144, `한글` in Korean), a punctuator to toggle on/off Korean input mode
- `LANGUAGE2` (0x91 = 145, `한자` in Korean), a punctuator to translate a Korean character to Chinese character

[HID codes](https://www.usb.org/sites/default/files/hut1_22.pdf)

If those keys are supported by Bazecor, it will be really convenient for Koreans.

**Describe the solution you'd like**
- Support Korean language in the Preferences page

**Describe alternatives you've considered**
N/A

**Additional context**
I've created a change set based on the  [development](https://github.com/Dygmalab/Bazecor/tree/development) branch (545f9a4225712b874e945e713a6553a1a4622124) .
You may find a pull request at https://github.com/TaeksuKim/Bazecor/pull/3 . 
Please refer attached screenshots.

May I create a pull request to [development](https://github.com/Dygmalab/Bazecor/tree/development) branch?

( Related issue is #304 )

**Comment by javierguzman** [comment]
Thanks @TaeksuKim for your support. I have already created a PR and if everything is ok, it will be available for the next release :)

**Comment by TaeksuKim** [comment]
@javierguzman Thanks for your effort 👍 

I was feeling a little bit worry that my PR had been created too long time ago. Thus, there might be misunderstandings or conflicts with current `development` branch.... but I've found that you've already fixed conflicts by yourself ( #466 ) I appreciate.
(Yes, you are right. Exactly same with US keyboard with just two extra keys :D )

I'll happily wait the merge and new feature to support Korean language 😸 

Thank you, now you may freely close this issue.

**Comment by javierguzman** [comment]
Hello @TaeksuKim there is a new release with the Korean layout, just to let you know. I hope everything works ok for you :) Again thank you!

p.s. I close this issue

**Comment by TaeksuKim** [comment]
@javierguzman Thanks for the notice. I've updated **Bazecor** and checked that all works!!!
