### ISSUE TITLE
LED layout doesn't match keyboard layer when switching

### ISSUE THREAD

**Issue by panoskittles** [Dygmalab/Bazecor#39]
I have 3 layers set up with corresponding LED underglow colors - Layer 0 blue, Layer 1 green, and Layer 2 red.  My "Lock To-" keys are set up on Layer 0 like this:

![lock-to-keys](https://user-images.githubusercontent.com/60662685/73763515-bd680500-472e-11ea-8d89-5ce01b1efb24.png)
Both of those thumb keys are set to Transparent on Layers 1 and 2.

Switching between Layer 0 to either Layer 1 or 2 works fine.  However, when I'm on Layer 1 and hit the Lock to 2 key, the LED underglow changes to Layer 2 red but the keyboard layout is still Layer 1.  Hitting Lock to 2 again changes the LED back to Layer 1 green, and the keyboard layout is still Layer 1.  

If, when starting on Layer 1, I hit Lock to 2 (color changes to Layer 2 red, layout is Layer 1) and THEN hit Lock to 1, the keyboard layout now matches Layer 2 (and the color is still Layer 2 red).

If I start on Layer 2 and hit the Lock to 1 key, the color does NOT change to Layer 1 green but the layout does.  If I hit Lock to 2 after Lock to 1, the color updates to match the layout.

Sorry, I know all this reads a bit confusing - let me know if I need to explain it differently!

**Comment by algernon** [comment]
Can you try pressing the "next led effect" key a few times, basically to cycle through the effects, back to the customised one? Do the colors change to the correct ones, once cycled back?

**Comment by panoskittles** [comment]
No, the "next led effect" key doesn't change anything.  

The Layer 1 I'm using is the default, so that key is set to the Right Arrow.

In the first situation I have starting at Layer 1, the color updates but the keyboard layout does not, which means I'm still on Layer 1.  In the second situation where I start on Layer 2, the keyboard layout updates but the color does not, meaning I'm again on Layer 1 where the "next led effect" key is the Right Arrow key functionally.

Here, I put together a little step by step of what is happening, hopefully it helps clear things up a little more.  The correct Layer/color combinations are 0/blue, 1/green, 2/red.

![step-by-step](https://user-images.githubusercontent.com/60662685/73770918-84359200-473a-11ea-8d60-f5d3aec1b6c0.png)

**Comment by panoskittles** [comment]
The latest update with "Lock to Layer" replaced with "Move to Layer" has fixed this issue for me.  Thanks for all your hard work, Dygma!
