### ISSUE TITLE
Key and color assignments shift between power cycles

### ISSUE THREAD

**Issue by matthewepler** [Dygmalab/Bazecor#413]
**Describe the bug**
After saving a layout and using it for some time, when I unplug and re-plug-in my keyboard, the positions have moved or been re-assigned in unpredictable ways. Usually it's 4-5 key assignment or colors that have moved just one space over. 

**To Reproduce**
1. Go to keyboard editor. 
2. Assign a key and color
3. Save
4. Power cycle board
5. Observe key shift -- note, this doesn't always happen. About 2-3 times a week. 

**Expected behavior**
The key assignments and colors are as they were saved. 

**Screenshots**

<img width="1409" alt="Screenshot 2023-04-12 at 7 36 33 PM" src="https://user-images.githubusercontent.com/1224277/231609487-bc0535bd-1ccf-4583-ab2f-1aba395ca57d.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Bazecor Version: 1.0.0-RC

**Additional context**

**Comment by javierguzman** [comment]
Hello! Does this still happen with lastest Bazecor versions? Thanks!
