### ISSUE TITLE
Clicking "Software update" on linux doesn't do anthing

### ISSUE THREAD

**Issue by EdvinOlofsson** [Dygmalab/Bazecor#42]
**Describe the bug**
See title

**To Reproduce**
1. click hamburger menu in Bazecor
2. click Software update

**Expected behavior**
I expect a software update/wizard to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Bazecor Version: 0.1.0

**Additional context**

**Comment by algernon** [comment]
This is something we're working on. The next version of Bazecor will still have the menu, but for the time being, it will be disabled. We hope to add an updater for the release after that.

**Comment by EdvinOlofsson** [comment]
Okey, sounds good! Thank you

**Comment by AlexDygma** [comment]
This feature is already in a working state in Bazecor 0.2.2+, so closing the issue...
