### ISSUE TITLE
Uninstaller stuck trying to close Bazecor, but Bazecor is not running

### ISSUE THREAD

**Issue by staffann** [Dygmalab/Bazecor#426]
On windows 10 H22, with Bazecore 1.0.0 (also on 1.1.2), when running the uninstaller, it thinks that Bazecor is running and tries to close it. Since Bazecor is not really running, it fails.

![image](https://github.com/Dygmalab/Bazecor/assets/11695024/79563e91-db7b-4afc-bac4-4d916fc99f30)

![image](https://github.com/Dygmalab/Bazecor/assets/11695024/879c8552-9fd7-49a3-bfd0-cd200033eec5)

Since the installer runs the unstaller, this blocks installation of a newer version.
A workaround seems to be to rename the folder C:\Users\UserName\AppData\Local\Programs\BAZECOR since the installer then goes ahead and seems to install the new version just fine.

**Comment by AlexDygma** [comment]
We updated all the packages so the new installations should work smoothly and not generate this problem anymore, the old installation may still require you to remove it via manual intervention, but test it out and comment here if it happens
