### ISSUE TITLE
Super Keys Incorrectly Modify Key and Color Mappings on macOS

### ISSUE THREAD

**Issue by waldronmatt** [Dygmalab/Bazecor#431]
**Describe the bug**
Mapping any key to a super key and saving those changes incorrectly modifies the key mappings and colors of the current and all other layers.

**To Reproduce**
1. Click on any key on any layer.
2. Choose a super key and save the layer.
3. See how the key mappings and colors are incorrectly modified.

**Expected behavior**
I expect that the keys and colors are not modified.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.5
 - Bazecor Version: 1.1.1

**Comment by javierguzman** [comment]
Hello @waldronmatt! It sounds weird; Have you tried with latest version of Bazecor? I have tried with 1.1.2 right now and it does not happen.

**Comment by waldronmatt** [comment]
Thanks I'll have to test out the newest version. Will report back if that's happening on my end still.
