### ISSUE TITLE
"Bazecor" can't be opened because Apple cannot check it... (MacOS Monterey) 

### ISSUE THREAD

**Issue by Nuru** [Dygmalab/Bazecor#442]
**Describe the bug**

After installing Bazecor 1.1.2 on macOS Monterey 12.6.6, it will not open. The error message is

> "Bazecor" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Screenshots**

![image](https://github.com/Dygmalab/Bazecor/assets/2793313/3dc670c5-7aa6-48ac-940b-a57a2ff008c1)

**Desktop (please complete the following information):**
 - OS: macOS 12.6.6
 - Bazecor Version: 1.2.2

**Comment by javierguzman** [comment]
The very first time you open it you need to right click on it and click open. We are currently upgrading Bazecor so this does not happen. Please, let us know if you do not achieve to open it!

**Comment by Xaelias** [comment]
This is happening to me as well on a mac w/ silicon. Tried right-click + open, tried to `Open Anyway` in `Privacy & Security`. To no avail.

**Comment by javierguzman** [comment]
Hello @Xaelias so if you right-click on the installer and open through the context menu then it does not work? Please could you let me know what version of Bazecor are you using? Also your MacOS version please

**Comment by Xaelias** [comment]
@javierguzman Whatever the version from the dygma website is. It looks like 1.1.2.

**Comment by GazHank** [comment]
It might be worth checking the app security settings you have configured within the system preferences per https://www.wikihow.com/Install-Software-from-Unsigned-Developers-on-a-Mac
