### ISSUE TITLE
Bazecor 0.2.0 countdown goes negative during flash upgrade

### ISSUE THREAD

**Issue by PetterS** [Dygmalab/Bazecor#46]
First Bazecor 0.2.0 failed to update the firmware, but the keyboard was completely unresponsive in the blue pulsating mode.

I then restarted Bazecor 0.2.0 and it said that the firmware had to be upgraded right now.

![Capture](https://user-images.githubusercontent.com/772305/74734065-0a2efe00-524e-11ea-90c3-f22e817f88de.PNG)

The countdown immediately went negative and never finished. This happened again after restarting Bazecor.

After unplugging and then replugging the keyboard I was at least able to use it again. But I cannot upgrade the firmware.

**Comment by PetterS** [comment]
Some errors during flash seems to only be logged to the console and then ignored: https://github.com/Dygmalab/Bazecor/commit/8b7673fe6e12a30141641bb91bfbe4396af8a6eb
How can I see the console logs in the app?

**Comment by darrenph1** [comment]
I saw this also. I was able to flash the keyboard by pluging it in while holding the esc key and then running Bazecore which wanted to update the keyboard right away.

**Comment by PetterS** [comment]
@darrenph1 so did that fix the issue? Which version did you update to?

**Comment by AlexDygma** [comment]
I have been able to reproduce this with bazecor 0.2.4, so the bug is still present, will try to fix this for the next revision.
