### ISSUE TITLE
Firmware version number inconsistency

### ISSUE THREAD

**Issue by GazHank** [Dygmalab/Bazecor#462]
**Describe the bug**
Prompt to update firmware when existing version is current.  The same firmware appears to show as 1.0.9beta vs 1.0.0-beta.9 (installed vs available)

Is there an inconsistency with now the version numbering is being read from the firmware vs the hex files?
**To Reproduce**
With firmware 1 beta 9 installed
navigate to firmware update

**Expected behavior**
If current version is the latest then this should be a reflash, not a fresh install

**Screenshots**
![image](https://github.com/Dygmalab/Bazecor/assets/64541249/a9a6c2be-f65b-4677-b60a-e26d73f9366c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Bazecor Version: 1.3.0

**Additional context**
Even after reflashing there seems to be a difference in the version numbering between the installed firmware and the available firmware

**Comment by GazHank** [comment]
Version 1.1.2 doesn't seem to display this issue:

![image](https://github.com/Dygmalab/Bazecor/assets/64541249/c290072f-613d-4a1b-a9ec-c9c106b2f45b)

However it does look like 1.2.1 does display the same issue

**Comment by AlexDygma** [comment]
Yes @GazHank! that's because the version was not named following SemVer conventions, which we follow no, so i adapted the name but the actual FW is the same, but it seems i should also adapt the name if not it's not working properly!

Thanks for the Tip ;)
