### ISSUE TITLE
Release for Apple Silicon missing

### ISSUE THREAD

**Issue by MarcelBochtler** [Dygmalab/Bazecor#480]
While the changelog for 1.3.1 states:

> Bazecor now runs natively on M1 Macs, and it's properly signed.

There is no arm64 binary available, and the x86 binary is only x86 not multiarch:
![image](https://github.com/Dygmalab/Bazecor/assets/4022103/b5f65097-4965-457b-8876-dfd01ca23f25)

**Comment by AlexDygma** [comment]
That's a good one, we forgot to add the arch universal flag to the new packager 😅 it's being worked on in the PR #482
