### ISSUE TITLE
Crash when recording macro (macOS)

### ISSUE THREAD

**Issue by hammittd** [Dygmalab/Bazecor#487]
**Describe the bug**
Bazecor crashes when I click Record Macro

**To Reproduce**
1. Go to Macro Editor
2. Click on Record Macro
3. Click Start record
4. See prompt to enable Bazecor to control the computer with accessibility features
5. Bazecor crashes before I can change any settings
6. See `Bazecor quit unexpectedly` error 

**Expected behavior**
To be able to record a macro

**Screenshots**
Happens when I click the "Start record" button:
![image](https://github.com/Dygmalab/Bazecor/assets/48220007/6c8f60eb-1c76-4fcb-8a37-cbea34b9b140)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.6.7 (21G651)
 - Bazecor Version: Version 1.0.0-RC (1.0.0-RC)

**Additional context**
From macOS problem report:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Bazecor [6270]
Path:                  /Applications/Bazecor.app/Contents/MacOS/Bazecor
Identifier:            com.dygmalab.bazecor
Version:               1.0.0-RC (1.0.0-RC)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-10 21:03:34.7149 -0500
OS Version:            macOS 12.6.7 (21G651)
Report Version:        12
Anonymous UUID:        97F84ED3-80EE-E892-B979-5F514358774D

Sleep/Wake UUID:       481463E4-5621-472F-9F09-F25E7CCA9466

Time Awake Since Boot: 170000 seconds
Time Since Wake:       35789 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
```

**Comment by javierguzman** [comment]
Hello @hammittd! Thanks for reporting; Have you tried with more recent versions of Bazecor? I think you are using 1.0.0-RC

**Comment by alexpargon** [comment]
Hello @hammittd 

Does this issue still present in newer versions of Bazecor?

**Comment by alexpargon** [comment]
feel free to reopen this when there is more info @hammittd !
