### ISSUE TITLE
Cannot flash new firmware updates

### ISSUE THREAD

**Issue by Elsie19** [Dygmalab/Bazecor#500]
**Describe the bug**
I an unable to flash any firmware version through the appimage.

**To Reproduce**
Add the udev rules.
Run the appimage.
Navigate to the <kbd>Firmware Update</kbd> table.
Click <kdb>Update now</kdb>.

**Expected behavior**
For the firmware to flash.

**Screenshots**
https://github.com/Dygmalab/Bazecor/assets/58742515/acb23540-10e0-43ba-885d-9e9efc4c139f

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Bazecor Version: 1.3.2

**Comment by piotrgondek** [comment]
I have the same issue.

**Comment by Elsie19** [comment]
Somehow it fixed itself!

**Comment by piotrgondek** [comment]
I still have this issue:


https://github.com/Dygmalab/Bazecor/assets/10886052/437a7896-5da4-4b9a-9b13-d952688b8ae5

**Comment by piotrgondek** [comment]
It's working :)
