### ISSUE TITLE
Bazecor 0.2. Is missing '<' key on Nordic layout.

### ISSUE THREAD

**Issue by sasumaki** [Dygmalab/Bazecor#51]
**Describe the bug**
There is no way to use  < on nordic layout on Bazecor 0.2. It's obviously wrong.

**Screenshots**

![image](https://user-images.githubusercontent.com/10545809/75462989-ce064680-598d-11ea-8c8b-bdbbf5c185b3.png)
![image](https://user-images.githubusercontent.com/10545809/75463082-f1c98c80-598d-11ea-8f30-e7825069b661.png)

**Desktop (please complete the following information):**
 - OS: Windows & Macos
 - Bazecor Version: 0.2

**Comment by sasumaki** [comment]
Also trying to override the key in the layer json is not working.

**Comment by jobor019** [comment]
Did you try the "|" symbol? This seems to be mapped to keycode 53 (`grave_accent_and_tilde`) which is what the "<" key corresponds to on Nordic ISO (MacOS).


![image](https://user-images.githubusercontent.com/28217154/75634608-960e3600-5c0f-11ea-8271-32fb609db96c.png)

**Comment by sasumaki** [comment]
Its wrong. 
Pressing that button gives "§"
Shift modifer: °
Alt modifire: ¶
Shift-alt: •

**Comment by ekakela** [comment]
Hi @sasumaki I use Finnish as my main language on Raise, the "Non-US \" is what provides the <>| functionality on Nordic layout, it is just labelled really confusingly

**Comment by sasumaki** [comment]
Thanks. It's in fact mapped in "Non-US" which is probably wrong and should be fixed at some point. But I'm happy now that it works

**Comment by HomerSp** [comment]
Agreed, Non-US \ is really confusing and it should probably be renamed to ISO <> as that's what it will generally be used for. @AlexDygma any inputs on this?

**Comment by AlexDygma** [comment]
Hello @HomerSp!, after reviewing this, i discovered all the keymaps for the languages are a mess, so to fix this we will have to alter this in each language layout specifically, just putting this in the punctuations.js file will affect all languages/keys in the same way and we should do this for each language individually to do it properly.

this is a 2 days task so it will take me some time to tackle this 😓

**Comment by HomerSp** [comment]
Ah yes, I see what you mean - it would indeed make more sense to put this in the separate keymaps. And I have to agree, they do look a bit messy :(
