### ISSUE TITLE
The Bazecor doesn't recognize the keyboard.

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [Dygmalab/Bazecor#52]
Kubuntu 18.0.4 LTS
The Bazecor doesn't recognize the keyboard.

The problem is that /dev/ttyACM0 is owned by root:dialout.
Adding my user to the dialout group and relogging in solved the problem.

**Comment by AlexDygma** [comment]
Great!, this issue is related to #26 and that's closed as now Bazecor displays a message to alert the user it has insufficient permissions to access the serial interface.
