### ISSUE TITLE
Long-pressing a Switch To Layer key => Move To Layer

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [Dygmalab/Bazecor#53]
Long-pressing a "Switch To Layer" key could produce a "Move To Layer" event if no other keys are pressed before the configurable timeout.
This way you can spare key assignments (I use 3 layers).

**Comment by GazHank** [comment]
I believe this feature request has been addressed with the introduction of "one shot layer" keys (a few releases ago).  The usage is slightly different but the resulting functionality is the same as requested.
