### ISSUE TITLE
dev: yarn install fails in Windows and WSL

### ISSUE THREAD

**Issue by unional** [Dygmalab/Bazecor#530]
**Describe the bug**

```sh
yarn

error /.../Bazecor/node_modules/drivelist: Command failed.
Exit code: 127
Command: prebuild-install --runtime napi || node-gyp rebuild
Arguments: 
Directory: /.../Bazecor/node_modules/drivelist
```

This is due to my `wsl2` is missing `node-gyp`. It shows if I run `yarn --verbose`:

```sh
yarn --verbose

...
Command: prebuild-install --runtime napi || node-gyp rebuild
Arguments:
Directory: ...\Bazecor\node_modules\drivelist
Output:
prebuild-install warn install No prebuilt binaries found (target=8 runtime=napi arch=x64 libc= platform=win32)
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.
```

The way to fix this is installing `node-gyp`: `npm i -g node-gyp`.

I can create a PR to add this in the readme.

**Comment by unional** [comment]
On Windows (outside of WSL2), also need python3 (as a dependency of using `node-gyp`), which can be installed using `winget`: `winget install python.python.3.10.0`.

Python 3.12 doesn't work as it fails with `Module Not Found 'distutils'`

UPDATE: running `yarn start` in Windows comes up with a blank screen, with the following error on the server side:

```sh
update-electron-app config looks good; aborting updates since app is in development mode
CHECKING BACKUP FOLDER VALUE ...\Dygma\Backups
[23860:1014/120426.010:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
[23860:1014/120452.059:ERROR:CONSOLE(1)] "Request Storage.getStorageKeyForFrame failed. {"code":-32602,"message":"Frame tree node for given frame not found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

**Comment by unional** [comment]
in wsl:

```sh
../libusb/libusb/os/linux_udev.c:28:10: fatal error: libudev.h: No such file or directory
  28 | #include <libudev.h>
  |          ^~~~~~~~~~~
  compilation terminated.

# needs
apt-get install libudev-dev
```

**Comment by alexpargon** [comment]
Hey there @unional !! 

You are right! the readme should have updated install instructions! the issue that Python has right now is good to mention even tho it will eventually be fixed.

if you want you can do this or I will do it in your stead, it will take me a bit of time as we are trying to get Bazecor up to speed and stable enough for all the Defy users!

**Comment by unional** [comment]
NP, I just try to set things up so that I can contribute.

Either ways are fine. 🌷

**Comment by alexpargon** [comment]
Thanks for that @unional!

we really appreciate it 🤗
