### ISSUE TITLE
Can't exit Preferences after changing settings in v1.3.6

### ISSUE THREAD

**Issue by jacobcassidy** [Dygmalab/Bazecor#552]
With a fresh install of Bazecor 1.3.6, if I go to Preferences, then change a setting, such as toggling the "Chrome Tools" on and back off again, then try to leave the Preferences, I get a "Unsaved changes" popup that tells me to save or discard my changes before leaving. The issue is both the save and discard buttons are inactive/grayed out so I can't do anything except quit the app and reload it.

I'm using Apple M1 with arm64 version of Bazecor 1.3.6 on macOS 14.

![unsaved](https://github.com/Dygmalab/Bazecor/assets/1895973/5f33d709-190e-4486-a821-dc916138d79c)
![grayed out buttons](https://github.com/Dygmalab/Bazecor/assets/1895973/9356e3a5-80df-4c97-83eb-e252cb75c334)

**Comment by alexpargon** [comment]
Nice one! @jacobcassidy 

will fix this one for the next RC candidate of 1.3.7, probably released on monday ;)

thanks for tipping us up!
