### ISSUE TITLE
Bazecor-1.3.6-arm64.dmg JavaScript Error

### ISSUE THREAD

**Issue by helicos6** [Dygmalab/Bazecor#553]
**Describe the bug**
JavaScript Error notice when Bazecor-1.3.6-arm64 app is launched.

**To Reproduce**
Launch Bazecor-1.3.6-arm64 on M1 Mac

**Expected behavior**
Should not give JavaScript Error.

**Screenshots**
![image](https://github.com/Dygmalab/Bazecor/assets/34452093/db4d2c0b-9767-47e5-be37-e85f9a4f8ff1)

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2 (22G91)
 - Bazecor Version: Bazecor-1.3.6-arm64

**Additional context**

**Comment by alexpargon** [comment]
@helicos6 i can't reproduce your issues in my MacM1, the error says that the installer has 'x86-64' and there are two installers for MacOS, as you confirm below you are using the right version, but just in case can you delete the local version of Bazecor installed on your computer and reinstall using this link? https://github.com/Dygmalab/Bazecor/releases/download/v.1.3.6/Bazecor-1.3.6-arm64.dmg

hope it solves it for you! if not, it could be a Rosetta thing, we will see!

**Comment by helicos6** [comment]
@alexpargon I removed the previous installation of Bazecor and installed again using the link you shared. The issue appears to be gone now. Thanks!
