### ISSUE TITLE
The APP asks to save layout changes in situations where there are no changes.

### ISSUE THREAD

**Issue by MasteringBOX** [Dygmalab/Bazecor#565]
**Describe the bug**
This happens in the Standard View in LayoutView. There is a similar issue in Macros as well. 
If you go into the standard view of a key and then press discard changes, the changes are discarded but the app calls StartContext() so the app forces you to save or discard again to change navigation.

**To Reproduce**
1. Go to 'Layout Editor'
2. Click on any key with the standard view on
3. Click on Discard Changes

**Expected behavior**
The discard and save buttons on the top right should be disabled, as there is nothing to discard or save.
When navigating to another page the pop-up window should not show. 

**SOLUTION**
I'm not familiar with this repository, but in LayoutEditor.js we have CloseStandardViewModal function that in line 1745 calls onKeyChange. This line should be removed to resolve the issue. onKeyChange updates the state and also calls StartContext() causing this issue. If onKeyChange has to be called for a speficic reason that I have missunderstood, it should still not call StartContext if called from CloseStandardViewModal (simple conditional should solve this).

**Feature Request**
The pop-up modal requesting to save or discard changes should have the option to save or discard changes instead of going back only, would improve usability.

**Screenshots**
Request if consider necessary.

**Desktop (please complete the following information):**
Will happen in all devices.

**Comment by alexpargon** [comment]
Hey there @MasteringBOX !

Thanks for the tip, I have a few more of these located on the preferences view, i will probably tackle them first thing next week

**Comment by zoehneto** [comment]
I think this is the same issue as #386
