### ISSUE TITLE
Mouse movement is very slow

### ISSUE THREAD

**Issue by landrito** [Dygmalab/Bazecor#57]
**Describe the bug**
Mouse  movement with the Raise starts very slow and accelerates to top speed in multiple seconds. 

**To Reproduce**
Use any of the mouse movement keys.

**Expected behavior**
The ability to alter the initial speed, acceleration ratio, and top speed. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.0

**Comment by landrito** [comment]
I think ideally all of these values could be configurable: 
https://github.com/keyboardio/Kaleidoscope-MouseKeys/blob/master/src/Kaleidoscope-MouseKeys.cpp#L25-L36

**Comment by landrito** [comment]
@algernon any news on this?

**Comment by sos0** [comment]
> I think ideally all of these values would be configurable:
> https://github.com/keyboardio/Kaleidoscope-MouseKeys/blob/master/src/Kaleidoscope-MouseKeys.cpp#L25-L36

This file is no longer accessible. Can you update the link?

**Comment by landrito** [comment]
https://github.com/keyboardio/Kaleidoscope/blob/master/src/kaleidoscope/plugin/MouseKeys.cpp#L28-L39

**Comment by underscorephil** [comment]
I would also love to see this. It would greatly improve the usefulness of mouse bindings.

**Comment by AlexDygma** [comment]
Hello @underscorephil @sos0 @landrito 

The mouse speed improvement was integrated in the changes for Bazecor version v0.2.3

if you are interested please test the latest version!

**Comment by landrito** [comment]
Thanks @AlexDygma,

I saw https://github.com/Dygmalab/Raise-Firmware/pull/6/files and have been using this to as a place to customize those mouse speeds. I encountered a problem though, it seems that the master branch of Raise-Firmware doesn't seem to have macro functionality in place. Am I missing a branch that the default hex is built off of?

**Comment by AlexDygma** [comment]
@landrito !

i forgot to tell you this was updated a while ago :) now you can compile with the latest verison of the firmware being feature full!
