### ISSUE TITLE
Layer shifting and moving on one key

### ISSUE THREAD

**Issue by aepfli** [Dygmalab/Bazecor#59]
**Is your feature request related to a problem? Please describe.**
Currently it seems not to be possible to use one key for moving and for shifting to a layer. there needs to be two different keys setup for this

**Describe the solution you'd like**
It would be cool to be also possible to add the shift functionality for holding a key to keys assigned to layer moving. This would allow a really flexible and easy way for spontanious switching or shifting based on the use case. Like during development of software when you suddenly need the numblock and cursor keys more, it would be cool to use the same button which is used when shifting to the cursor keys.

**Comment by aepfli** [comment]
possibly links to #53

**Comment by GazHank** [comment]
I believe this feature request has been addressed with the introduction of "one shot layer" keys (a few releases ago).  The usage is slightly different but the resulting functionality is the same as requested.

**Comment by staffann** [comment]
@GazHank I intepret this as combining layer shift and layer lock in one key (hold for shift, tap for lock). That is also what I am looking for. The OSL does not do a layer lock.

**Comment by alexpargon** [comment]
You can now do this with Superkeys in it's latest iteration (beta) it will be introduced in the stable FW as soon as it's polished! so i will close this (As Bazecor already supports that configuration when using the beta channel)
