### ISSUE TITLE
Bazecor crashes

### ISSUE THREAD

**Issue by brandon-leapyear** [Dygmalab/Bazecor#62]
**Describe the bug**
When I go to configure the keyboard, the layers go from 2 to 11, and I can't select layers 0 or 1. Furthermore, if I click on Layer 10 or 11, it crashes.

[console log](https://github.com/Dygmalab/Bazecor/files/4327076/bazecor.log)
<img width="1211" alt="Screen Shot 2020-03-12 at 4 24 21 PM" src="https://user-images.githubusercontent.com/27799541/76575957-f443e000-647d-11ea-8512-d8c696135332.png">

I think my keyboard is in a bad state. I tried uninstalling and reinstalling Bazecor, but the issue is still there.

The one thing I remember doing is when I was editing the keyboard before, I clicked "save layout", which turned into a green checkmark, which I clicked again, which crashed the app after a few minutes. I put on my QA hat and kept clicking the "save layout" button (after it turned into a green checkmark), which crashed the app and put my keyboard in this state.

Is there a way to factory reset my Neuron? It doesn't seem like there's a way.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also include a log from the "developer console". You can access it by pressing `Control + Shift + I`. When it appears, right click inside it, and select "Save as", and attach the saved file to this report.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Bazecor Version: 0.1.0

**Additional context**

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Update: turns out if I went to "show hardcoded layers", it shows layers 0 and 1 as locked. Why is this the case?

If I click "use custom layers only", then layer 0 and 1 become layers -1 and -2, and I can now edit layer 0

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Also, my LED lights are no longer respecting the configuration

**Comment by LuisSevilla** [comment]
Hey Brandon, following up here to your email.

Turn off "Show hardcoded layers" and on "Use custom layers only".

Does it work now?

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

That's what I've been doing for now, but the LEDs still don't reflect the config.

What does hardcoded/custom mean? Is there a way to go back to the way it was configured out of the box?

**Comment by LuisSevilla** [comment]
The keyboard works fine, but the LEDs don't reflect your colormap configuration, correct? What color/s does your backlight and underglow have?

To be honest, the best person to answer precisely what hardcoded/custom mean is @algernon, but I'll do my best. Hardcoded layers are layers that you can't modify. The custom ones are the ones that you can play with.

You can import the default factory [layer 0](https://docs.google.com/document/d/1EZ5ZyraVVvsA6vmvYbm5W88L0G3g1utbyJeRrMhfIw8/edit) and [layer 1](https://docs.google.com/document/d/1EZ5ZyraVVvsA6vmvYbm5W88L0G3g1utbyJeRrMhfIw8/edit) layers. Copy the text in those links and import it by hitting the Import/Export icon (similar to this symbol ↨) on the top right corner of Layout & Colormap editor.

Please, tell me if you were able to make your Raise work normally. If you couldn't, we can always reset it and flash the firmware again.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

> The keyboard works fine, but the LEDs don't reflect your colormap configuration, correct? What color/s does your backlight and underglow have?

Correct. The keyboard currently has blue for everything, even though layer 0 has some keys with other colors. And when switching to layer 1, the color stays the same, even though the config says the underglow should be green.

> Please, tell me if you were able to make your Raise work normally. If you couldn't, we can always reset it and flash the firmware again.

I tried resetting it, but it never works. It usually says "could not find bootstrap module". Also, it didn't seem to work when I had the ESC key remapped, but it got further (still didn't work) after mapping the ESC key back

**Comment by LuisSevilla** [comment]
Oh, that's really useful information. You've accidentally pressed "LED Effect Next" key. Press it a few more times and you will cycle out the LED effects. Maybe this [video](
https://www.loom.com/share/13d542c8b492408fa2d081ed74c71494) helps.

Have in mind that the recording of the keyboard is flipped. What you see as my left hand, it's actually my right hand.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Perfect! I guess I accidentally hit that key when I used the hardcoded Layer 0.

Can @algernon provide some context on default layers vs custom layers? What's the purpose of this?

I have custom layers turned on (because it won't work without it), and when I turn on hardcoded layers, I see layers -1 and -2. Is that still correct?

There's also the issue that started this whole thing, where clicking the "save" button repeatedly caused the keyboard to revert to hardcoded layers.

**Comment by AlexDygma** [comment]
> Perfect! I guess I accidentally hit that key when I used the hardcoded Layer 0.
> 
> Can @algernon provide some context on default layers vs custom layers? What's the purpose of this?
> 
> I have custom layers turned on (because it won't work without it), and when I turn on hardcoded layers, I see layers -1 and -2. Is that still correct?
> 
> There's also the issue that started this whole thing, where clicking the "save" button repeatedly caused the keyboard to revert to hardcoded layers.

Hello @brandon-leapyear !

Yes you are right, the hardcoded layers do not add anything for the user so i recommend you to hide them, in fact, in the newer keyboards we will distribute, this option will come preconfigured, so only if willingly, users may activate the visibility of default layers.

Ideally this layers won't be visible whatsoever as they only serve a purpose of recovering the default configuration for your raise, but that is a ton easier using the backup & restore functionality implemented in #112 

i'll close this issue cause it can be considered solved for now.
