### ISSUE TITLE
Enhance Backup-Abilities

### ISSUE THREAD

**Issue by scriptmode** [Dygmalab/Bazecor#63]
**Is your feature request related to a problem? Please describe.**
Making backup of layouts is cumbersome. But backups are important.
In case you have multiple keyboards or experimenting with layouts for example.

**Describe the solution you'd like**
- Allow full backup of all layers in one json-file. At the moment it's just one layer per export??
- Add Setting to define a directory to which backups are automatically dumped to.
- Add setting to give layouts a name. Just show the name in the editor and add some button for changing it.
- Save backups automatically on every press of "Save changes".
- Each backup should be a new file with date+timestamp.
- Add button to load a backup. Just give a filedialog which starts in the backup-directory.

**Comment by LuisSevilla** [comment]
Hey Scriptmode, thanks for your suggestion.

Currently, we are working on a layer sharing system that would include having a cloud backup. You'll be able to save your layers automatically or manually. You would be able to have the history of your modifications privately and share your "finished" layouts if you want to.

You can read more about it in [this Trello card](https://trello.com/c/Y5CC7Lu2/169-create-layer-sharing-system).

**Comment by scriptmode** [comment]
This reads like backup is cloud-only, nothing local? This would be unacceptable.

**Comment by LuisSevilla** [comment]
For our MVP, it's not planned to be stored localy.

**Comment by scriptmode** [comment]
Thanks for the Information. In this case I will start making other arrangements. You are free to close this Issue.

**Comment by GazHank** [comment]
For anyone else looking at this issue/ feature request; please note the the layout backup (single layer and all layers) is included in Bazecor.  The extra features mentioned which are not (yet?) included are cloud backup, labelling layers and autosave/ auto-backup.
