### ISSUE TITLE
"Modifier when held, normal key otherwise" not working

### ISSUE THREAD

**Issue by scriptmode** [Dygmalab/Bazecor#64]
**Describe the bug**
The option "Modifier when held, normal key otherwise" is not working when used for a key.
In fact the key is dead with this.

**To Reproduce**
1. Select a key, let's say Space.
2. Activate a modifier for it, let's say Control
3. Activate the Option "Modifier when held, normal key otherwise" for this key,
4. Save changes on keyboard

**Expected behavior**
When pressing the key with space for a short time, it should act like a space-key and insert a space.
When holding the key with space, it should act like a control-key, allowing to press other keys for a shortcut. For example Space-Key + n would be Control + n.

**Desktop (please complete the following information):**
 - OS: Debian Linux 
 - Bazecor Version: 0.2.0

**Additional context**
I checked with xev, when pressing the Space-Key, it receives nothing. Meaning it seems to be the key has no configuration at all.

**Comment by LuisSevilla** [comment]
Thanks for reporting about the bug.

I haven't been able to reproduce it in my Windows machine using Bazecor 0.2.0 too.

Can you try using Bazecor in a Windows machine and see if you still have the issue? Maybe it's a Linux Bazecor related thing.

Maybe @algernon can take a look. Linux is his main OS.

**Comment by scriptmode** [comment]
Same problem with Windows. I even used the windows-Version of Bazecor for this and tried some other keys. Same result, keys are dead.

**Comment by djl** [comment]
I'm also running into this issue. Dual-use keys don't show up at all in `xev` (or in my case, `wev`). This also seems to happen in Chrysalis.

**Comment by scriptmode** [comment]
Works now after upgrading to the newest Firmware from Bazecor 0.2.2.

**Comment by AlexDygma** [comment]
> Works now after upgrading to the newest Firmware from Bazecor 0.2.2.

Hello @scriptmode !

Thanks for following up :) as this is fixed in Bazecor 0.2.2 ill close this issue.
