### ISSUE TITLE
Ability to have different keys per operating system

### ISSUE THREAD

**Issue by EdSheranaway** [Dygmalab/Bazecor#642]
**Is your feature request related to a problem? Please describe.**
I have a work Mac and a personal Windows computer, I'd like to be able to use my Dygma Raise differently on Windows and Mac when coding, so it would be nice if there was an option to have special key-bindings for each operating system

**Describe the solution you'd like**
Add an option to bind this key to a different functionality per OS, could be a toggle in the keys menu.

**Describe alternatives you've considered**
Could use separate layers for each device but it's more tedious and where's the fun in that.
**Additional context**
I'd love to contribute and help build this if it's something the team thinks is a good feature :)

**Comment by rbutera** [comment]
I have a dedicated mac layer (and mac "alt" layer which has navigation and things like volume up and down) as well as a dedicated windows layer (and corresponding "alt").

While I think I would find this feature somewhat useful, I really don't think it will be implemented, and I think developer time could be used in better ways.

My reasoning is thus: The functionality you are seeking is very easily achievable through software. For example, Mac has the ability to swap the modifier keys directly in the OS. More ambitious modifications can easily be implemented using Karabiner.

Furthermore, I don't think the Neuron is able to detect the operating system that it is connected to. I can't imagine how you could implement that on the hardware level. That leaves us with software detection, which means that you would need Bazecor open at all times. That doesn't sit right with me. I love that I can flash my Defy and not touch Bazecor. I love that i can connect my Defy to any computer and all of my macros, layers and superkeys come with me. Implementing the feature that you propose would sacrifice a lot of that.

In my opinion we should implement features that aren't easily achievable through other means. Let's stand on the shoulders of giants!

**Comment by GazHank** [comment]
The keyboard/neuron can detect the OS using the [HostOS Plugin](https://github.com/Dygmalab/Kaleidoscope-Dygma/blob/main/docs/plugins/HostOS.md), however there would need to be some design work on how the host information could be used.  I think the easiest would be to automatically switch the starting layer based on the host OS (if Linux default to layer 1, mac defaults to 2 etc), but I'm not sure if that is what you are looking for.

**Comment by EdSheranaway** [comment]
I understand @rbutera that's a very valid point.
@GazHank to your suggestion I think if we had that option it would be cool, default layer per OS and somewhere in the setting to set that, but I understand if that's not something that should be worked on

**Comment by rbutera** [comment]
> The keyboard/neuron can detect the OS using the [HostOS Plugin](https://github.com/Dygmalab/Kaleidoscope-Dygma/blob/main/docs/plugins/HostOS.md?rgh-link-date=2024-01-16T11%3A13%3A35Z)

@GazHank 

Forgive me if I am wrong, but as far as I can tell the HostOS plugin doesn't actually detect the OS, it remembers what OS the user has set from some other means, e.g. via a macro. 

I've done some digging on the kaleidoscope discussions on the plugin, and it seems a little unreliable.

**Comment by GazHank** [comment]
Thanks for the heads up, I'll try to take a look
