### ISSUE TITLE
Doubleclick key to open key config

### ISSUE THREAD

**Issue by scriptmode** [Dygmalab/Bazecor#65]
**Is your feature request related to a problem? Please describe.**
At the momen you select a key with one click (a second click deselects the key).
Then at the bottom of the window the configuration appears, with a button "key config".
Most of the time I go to key config to select a keycode. But as this button is right on the bottom of screen, while most keys are in the upper half oif the screen, I waste many time for moving mouse between keys and key config-button.

**Describe the solution you'd like**
Open the key config-dialog directly when double clicking a button.
The existing button can remain at the bottom for new users.

**Comment by LuisSevilla** [comment]
Hey, thanks for the suggestion. We are working on a different solution to reduce the amount of clicking, creating a bot panel menu that fits the screen while you are modifying your layouts. You can check it in [this Trello card](https://trello.com/c/0Pfv2wmP/59-create-bottom-panel-key-config-menu).
