### ISSUE TITLE
More flexible layer switching

### ISSUE THREAD

**Issue by brandon-leapyear** [Dygmalab/Bazecor#66]
It seems like "Lock to 1" and "Shift to 1" are not completely intuitive. My mental model is that the layers are like a queue, and when you shift/lock to a new layer, you add that layer to the queue, and then releasing/clicking again would remove the layer from the queue. To me, this seems like the most intuitive model of layers. It would also be great to have a key like "Move to 1" that would erase the queue and start the queue over at the new layer.

Currently, I can't do any of the following:
1. Use layer 9 as like a "Layer chooser", where I can designate a key on the keyboard to jump to a layer menu, where one key would jump me to layer 0, another to layer 1, etc.
2. Lock to a layer, but then allowing me to shift into other layers temporarily, while I'm locked on this layer

Specifically, it'd be nice to have one keyboard configuration for normal use, and then another configuration for using only half the keyboard.

**Comment by LuisSevilla** [comment]
I totally agree with you; the layer system is not intuitive. We are reworking it for Bazecor v0.3, and you'll be able to do what you mention.

I've updated the [Trello card](https://trello.com/c/xxPPDjq4/149-create-levels-plugin) with the feature specs. Feel free to comment or vote on any Trello card. We prioritize developing the ones that receive more votes.
