### ISSUE TITLE
Inconsistent icons and casing used for media buttons and apps

### ISSUE THREAD

**Issue by eikowagenknecht** [Dygmalab/Bazecor#663]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Dygmalab/Bazecor/assets/1475672/d5435dbd-035d-4462-8f6d-8d255a38ae2a)

Also the shuffle icon is just displayed as "Shuffle" on the keyboard instead of using a symbol.

Why is it sometimes all caps, sometimes a symbol and sometimes Camel Case?
![image](https://github.com/Dygmalab/Bazecor/assets/1475672/36c6c209-9a14-4231-9188-10ac41f548f0)

**Describe the solution you'd like**
Use consistent symbols.

**Comment by alexpargon** [comment]
@eikowagenknecht 

It seems the new icon set was not applied consistently when introduced on the keyboard picker. Will check this!
