### ISSUE TITLE
Development version fails on loading virtual keyboard file

### ISSUE THREAD

**Issue by 0rzech** [Dygmalab/Bazecor#669]
**Describe the bug**
Bazecor built from 6e3606b3eec93ccd0b064e55fac0dc9907a60329 (and possibly earlier) fails with `e.charCodeAt is not a function` when trying to load `VirtualDefy.json`.

**To Reproduce**
1. Build Bazecor from 6e3606b3eec93ccd0b064e55fac0dc9907a60329 .
2. Open Bazecor.
3. Click on `Use without a keyboard`.
4. Click on `Load file`.
5. Choose `VirtualDefy.json`.
6. See the error.

**Expected behavior**
File should be loaded properly.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Bazecor Version: 1.3.10-rc.2 .

**Additional context**
The error does not happen when loading `VirtualRaise*.json`.

**Comment by alexpargon** [comment]
Just fixed it!, try after pulling

**Comment by 0rzech** [comment]
It works, thanks!
