### ISSUE TITLE
Development version has problems with remapping thumb cluster keys

### ISSUE THREAD

**Issue by 0rzech** [Dygmalab/Bazecor#680]
**Describe the bug**
Bazecor built from 8364b314c9dbd37067a2ee7ca143267b2bf882c3 (and possibly earlier) has problems with remapping thumb cluster keys.

**To Reproduce**
1. Build Bazecor from 8364b314c9dbd37067a2ee7ca143267b2bf882c3 .
2. Open Bazecor.
3. Select some thumb cluster key on keyboard visualisation.
4. **Problem no. 1:** If thumb key has something assigned already, on the left of keyboard picker it still says `NO.KEY`.
5. Pick some key from keyboard picker.
6. **Problem no. 2:** Picked symbol is properly shown on keyboard visualisation, not on the left of keyboard picker, i.e. it remains `NO.KEY`.
7. Add some modifier, eg. `Alt Gr`.
8. **Problem no. 3:** Selected key on keyboard visualisation changes to `NO KEY`.
9. **Problem no. 4:** Clicking one-by-one thumb cluster keys on keyboard picker can occasionally dim the whole keyboard picker, though the keys on it remain clickable.

**Expected behavior**
Remapping thumb cluster keys should work as expected.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Bazecor Version: 1.3.10-rc.3

**Additional context**
The problem does not happen for alphanumeric keys.

**Comment by alexpargon** [comment]
Wow! @0rzech 

I wish I had read you before releasing the 1.3.10 stable 🤣 

Ill push a hotfix today to solve this.

**Comment by 0rzech** [comment]
Haha! No problem! 😉 At first I was surprised that you released anyways, but then I came to conclusion that maybe you had some hard deadline or just went YOLO 🤣, or that you release often enough just to fix in next iteration. 😉
