### ISSUE TITLE
Bazecor 1.3.10 can't add dual function keys to RH thumbkeys

### ISSUE THREAD

**Issue by kennethgillen** [Dygmalab/Bazecor#695]
**Describe the bug**
The option to add dual-functions, like 'hold for shift' etc, on my right hand side thumbkeys, doesn't seem to be available with Bazecor 1.3.10. If I downgrade to 1.3.9 the functionality comes back. 

**To Reproduce**
1. Go to 'layout editor'
2. Click on 'a currently transparent key in my right hand thumb cluster'
3. pick 'enter' for the key
4. Attempt to choose a dual-function modifier
5. See the mouse pointer icon 'can't do that' and buttons greyed out.

**Expected behavior**
Able to select 'enter' key with modifier 'Ctrl'

On further investigation, if I pick the 'single view' rather than standard view, I'm unable to assign any keys to the right thumb cluster if I 'discard changes', make a key in the left hand thumb cluster an 'enter' key, then move back to the right hand thumb cluster, and it's impossible to assign any keys to that cluster anymore.

**Desktop (please complete the following information):**
 - OS: Mac OS 14.3
 - Bazecor Version: 1.3.10
 
**Additional context**
It seems to work with the 
  - left thumb cluster keys
  - both main clusters' keys

**Comment by not-that-nda** [comment]
Same here but downgrading did not fix it for me. Maybe a firmware issue?
Dygma Defy keyboard here.

**Comment by golden-potion** [comment]
Same with me, using Mac, Linux, and Windows. Defy 1.2.6b and Bazecor 1.3.10

**Comment by alexpargon** [comment]
this is solved, pending to be released as 1.3.11, will do so today
