### ISSUE TITLE
Backslash not present in Spanish

### ISSUE THREAD

**Issue by Kawahal** [Dygmalab/Bazecor#70]
**Describe the bug**
When trying to configure a key to represent the symbol "\\", it is not present in Spanish layout. Trying to configure it via jason doesn't work, I suspect because they keycode is not present in the spanish keycode configuration [(link)](https://github.com/Dygmalab/Bazecor/blob/development/src/api/keymap/languages/spanish/spanish.js), and also might be repeated across multiple languages for different symbols. 

Also tried setting it up in English, but it writes "ç" instead. 

**To Reproduce**
1. Go to layout and colormap editor
2. Click on any key
3. Set language as spanish
4. Backslash symbol is not present

**Expected behavior**
"\\" symbol is present. 

**Desktop (please complete the following information):**
 - OS: macOS, Ubuntu
 - Bazecor Version: 0.1.0, 0.2.0

**Additional context**
Both OS are set to have Spanish input.

**Comment by keiyasssss** [comment]
Hello the symbol is present, you need to map "º" in any key and use it pressing "alt gr" and "º".

**Comment by Kawahal** [comment]
After testing, looks like the "º" key is actually mapped as "<" in the Spanish layout, so I can use altgr + "<" to get it. 

It would be nice to be able to map every key to a char without using this kind of combinations, tough. 

Anyways, closing this, thanks for the help.

**Comment by ciberado** [comment]
JFYI: at least in my case, I actually needed to follow the original suggestion (altgr+º).
