### ISSUE TITLE
Toggle LEDs On/Off only affecting Neuron on wired Defy

### ISSUE THREAD

**Issue by jbcaramar** [Dygmalab/Bazecor#703]
**Describe the bug**
When a key is set up to use the "Toggle LEDs On/Off" function on my wired Dygma Defy, it fails to toggle any LEDs except the ones on the Neuron. All the Defy keyboard LEDs remain on at all times.

**To Reproduce**
1. Use Bazecor to set up a "Toggle LEDs On/Off" key on wired Defy.
2. Attempt to use the key to toggle the keyboard LEDs on and off.
3. Only the Neuron LEDs are toggled on and off by the key. Keyboard LEDs always remain on. The keyboard LEDs *can* be turned off using the "Previous/Next light effect" function, but the Toggle function apparently doesn't affect the keyboard at all, apart from the Neuron.

**Expected behavior**
Expected keyboard LEDs to go completely dark and then come back on with alternating key presses.

**Screenshots**
[-1706583291519.log](https://github.com/Dygmalab/Bazecor/files/14092263/-1706583291519.log)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Wayland, Sway
 - Bazecor Version: 1.3.10, 1.3.11
 - Keyboard: Dygma Defy - Wired
 - Firmware: 1.2.6beta

**Additional context**

**Comment by alexpargon** [comment]
@jbcaramar is this fixed with Firmware 1.2.7-beta?

**Comment by jbcaramar** [comment]
Sorry. Had to re-find the steps for updating the firmware on linux ([#643](https://github.com/Dygmalab/Bazecor/issues/643)). This really needs to be fixed or better documented.

Yes, the 1.2.7-beta fixes the issue. Toggling on/off now works for the keyboard. Thanks! Closing.
