### ISSUE TITLE
Superkeys have "#1" key after saving

### ISSUE THREAD

**Issue by eikowagenknecht** [Dygmalab/Bazecor#715]
**Describe the bug**
I have this superkey:

![image](https://github.com/Dygmalab/Bazecor/assets/1475672/c88d7f3c-2026-4bf4-b272-7084622e3768)

I freshly created it and set hold and tap/hold.

After saving, 2tap/hold gets this mysterious "#1"

Also it doesn't do what I would expect it to do... but that's no new issue unfortunately.

**To Reproduce**

**Expected behavior**
2tap/hold should be no key

**Desktop (please complete the following information):**
 - OS: Win 11
 - Bazecor Version: Latest 1.4.0-rc1

**Comment by alexpargon** [comment]
@eikowagenknecht Going to take a look at this! 👀
