### ISSUE TITLE
Tryout software without keyboard

### ISSUE THREAD

**Issue by laped83** [Dygmalab/Bazecor#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
See that the software can offer without having bought the keyboard.  So instead of "no keyboard decteted" a demo option would be appreciated.

**Describe alternatives you've considered**

**Additional context**

**Comment by ASKemp** [comment]
Agree with above, it would also potentially allow contribution from those who haven't got their keyboards yet.

**Comment by NamespaceV** [comment]
Workaround:
https://dygma.com/pages/my-raise#opening
Shows movies with most views if you want to see how it looks like.

I agree some "Demo" Keyboard with hardware calls mocked could be nice.

But seeing colors on hardware makes much difference, 
and it is a software to configure colors and layouts on your keyboard...
so its not really useful without a keyboard...

**Comment by Lite5h4dow** [comment]
i agree but for another reason, i cant seem to get the dev environment working in windows for whatever reason but I can in WSL and since WSL doesn't have USB passthrough yet, I cant actually get into the software. its very frustrating.

**Comment by javierguzman** [comment]
You can know Bazecor without a keyboard
