### ISSUE TITLE
Configure ASCII chart in any layout

### ISSUE THREAD

**Issue by keiyasssss** [Dygmalab/Bazecor#77]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to put an ñ or ç when I'm using US layout

**Describe the solution you'd like**
I want to configure in one layer some of the special charts that I need. 
There should be a box in the key config section called "special characters" with a list that let me configure them in any key.

**Additional context**
Another option is let me map the ASCII code of the character to a key. Eg: alt+164 on  space key

**Comment by aepfli** [comment]
relates to #60 in my opinion - at least it has the same goal somhow

**Comment by javierguzman** [comment]
Closed as I consider this duplicated
