### ISSUE TITLE
Update to 0.2.2 looses all settings

### ISSUE THREAD

**Issue by u-hafner** [Dygmalab/Bazecor#78]
**Describe the bug**
Updating the firmware to 0.2.2 from 0.2.0 looses all my keyboard and light settings.
After the update the color scheme is black ! and highlights keys pressed.
Before that it was light blue (as delivered) and some keys where adjusted to my language needs. Especially layer 1.

**To Reproduce**
Use a customized keyboard setting in firmware 0.2.0 and update firmware.
- go to rainbow theme
- press start for countdown.
- press esc (before countdown ends)
- blinking neuron
- all black (?? unexpected but still pressing esc)
- used mouse to click on bazecor to see if it still working. suddenly dialog closes which showed firmware upload.
- release esc key
- Bazecor was not able to show keyboard settings. Not working correctly anymore.
- had to close and reopen bazecor.
- All black lights. Keyboard settings resetted!

**Expected behavior**
Old keyboard settings stay.
OR: WARNING before flashing that they will be lost.
AND: possibility to save and reload old settings 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.2

**Comment by AlexDygma** [comment]
Hello @u-hafner !

Clearly your flashing process went badly, the question is why, i have fixed some flashing issues in the latest 0.2.3+ Bazecor version, so if you could follow up this issue with your experience with the updated bazecor versions to be sure the bug is no longer present we would be able to close this with certainty.

for the time being i'll close this either way, you can comment here and i'll reopen it if the issue persist.

**Comment by u-hafner** [comment]
Hello @AlexDygma 

The 0.2.4 version was the first version that actually flashed without problems (as I already had problems with 0.2.0). so great - thanks.

Would love to give you more feedback about the 0.2.4 but flashing was about it that worked. As I seem to have a hardware problem it took 1-2 min until my Raise stopped working. So I unplugged it again waiting for a response from Dygma - haven't got one yet.
I reached out to Dygma about my other problem already 3 times in the last 4 weeks. But no one answered yet.

**Comment by AlexDygma** [comment]
Hello again @u-hafner !

I'm sorry to hear that, it's strange that you haven't got an answer from them as they usually don't take more than a day to reply to a new request.

Please contact them linking this GitHub issue so we can help you with your problem.

**Comment by u-hafner** [comment]
@AlexDygma This issue is not related to my hardware problem. I'll try contacting them again.
I think this issue with flashing is closed for me. As it worked as expected. Thanks again.
