### ISSUE TITLE
Installers Broken on Windows 11

### ISSUE THREAD

**Issue by jasonSchroeder89** [Dygmalab/Bazecor#780]
**Describe the bug**
The installers for versions 1.4.0-rc3 and 1.4.0-rc4 do not work on Windows 11 Home Edition.

A green box appears, but the app never opens.

Same behavior is observed for 1.4.0-rc2 installer, but app does open after green box disappears and when I open the application from either the Start Menu or a shortcut.

**To Reproduce**
1.  Download installer from Github
2. Run installer

**Expected behavior**
The installer would give some sort of information in GUI, install application, and allow application to be opened.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Edition
 - Bazecor Version: 1.4.0-rc2, 1.4.0-rc3, 1.4.0-rc4

**Comment by alexpargon** [comment]
we have seen this in other occasions related to AMD hardware, for whatever reason ( even tho I use that same hardware at home and i have not experienced those issues) we fixed them but they seem to reappear from time to time in some windows machines.

@jasonSchroeder89 can you please detail your hardware components? i think it will be helpfull

**Comment by jasonSchroeder89** [comment]
Processor: i9-11900H

Graphics: Intel Integrated Graphics

My work-device is a Dell XPS 15 Laptop. There is an on-board RTX 3050 Ti but I am not using it to power the display I am running Bazecor on.

**Comment by alexpargon** [comment]
@jasonSchroeder89 i tested this thoroughly before releasing 1.4.0 and it should be all ok, did you manage to test it again with the newer versions of Bazecor?

**Comment by jasonSchroeder89** [comment]
I have been able to get 2 new versions installed using the installer without needing to do a full-removal now: 1.4.0-rc6 and 1.4.2.

**Comment by alexpargon** [comment]
👍🏻 ill close this then!
