### ISSUE TITLE
Typo on release versioning schema? 

### ISSUE THREAD

**Issue by coolapso** [Dygmalab/Bazecor#783]
Versions have been following [semver](https://semver.org) Standard up to 1.4.0-rc.4 which is now 1.4.0-rc4. 

are you no longer following semver? is this the new standard or is just a typo? 

This breaks automation based on your versioning schema, such as the Arch Linux AUR Package. 

Thank you, for your time.

**Comment by alexpargon** [comment]
@coolapso Yes! you are right.

RC.5 is back on track and i replaced the name of the release, but not the tag, will do that later for consistency.
