### ISSUE TITLE
LED rainbow mode description for firmware update

### ISSUE THREAD

**Issue by gautamjain** [Dygmalab/Bazecor#79]
**Is your feature request related to a problem? Please describe.**

Bazecore says your Raise must be in LED Rainbow mode before proceeding with a firmware update.  It's not completely obvious if "Rainbow mode" refers to:

- the mode when all LEDs are the same color, but cycle through one color at a time
- the mode when all LEDs are different colors, and 

I suspect it is referring to the latter mode.  But because it's a firmware update, I'm a little hesitant to just try and see if that works.

**Screenshots**
![Screen Shot 2020-08-05 at 2 45 21 PM](https://user-images.githubusercontent.com/1161630/89467368-4b4a9a00-d72a-11ea-8745-9dd608cb1c2d.png)

**Describe the solution you'd like**
A picture of rainbow mode or a clearer description might be helpful.

**To Reproduce**
Menu > Firmware Update

**Desktop:**
 - OS: macOS
 - Bazecor Version: 0.2.2

**Comment by JoonasD6** [comment]
I'm bumping this for the same reason that it's weird description with a crucial process. "Why would led colours matter?" "Is Rainbow Mode some proper noun for some special mode? Is there a button for it on the keyboard? In the software?"

**Comment by javierguzman** [comment]
Old Bazecor, so I close this.
