### ISSUE TITLE
bazecor is not opened with Uncaught Exception

### ISSUE THREAD

**Issue by writeAheadLog** [Dygmalab/Bazecor#826]
**Describe the bug**
When I open Bazecor 1.4.0, I get the following error as shown in the screenshot below.

**To Reproduce**
1. Open Bazecor 1.4.0

**Expected behavior**
Bazecor opens normally

**Screenshots**
<img width="722" alt="image" src="https://github.com/user-attachments/assets/47f64f49-f4e0-4cfd-bf50-e5c4eea8941f">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Bazecor Version: 1.4.0

**Additional context**
My Mac is apple silicone arm64

**Comment by risa** [comment]
The same problem here ...  same macOS version, arm based Macbook Pro

**Comment by IsaacHach** [comment]
Also have this issue on my desktop running Windows 11 but not my Surface laptop running Windows 11. Error mentions the property "showDefaults" too.
![image](https://github.com/user-attachments/assets/87a691a7-3be0-4561-9e95-f0709741a364)

**Comment by writeAheadLog** [comment]
It still occurs in Bazecor 1.4.1.

**Comment by brodie2112** [comment]
I'm having this same issue, except I am on an Intel Macbook... 1.3.10 is fine, but any time I try to go to 1.4.0 or higher, I get this error when opening Bazecor. 

![Screenshot 2024-07-19 at 12 31 41 PM](https://github.com/user-attachments/assets/17e30a1b-71be-43a4-b4cd-656cdcad99e9)

**Comment by alexpargon** [comment]
Hello!

this is caused by an older configuration in your stored settings and the typed schema we added for the new release, this is solved just by doing a clean install -> https://support.dygma.com/hc/en-us/articles/360015643358-How-do-I-clean-install-Bazecor

either way I will add checks to avoid this going forward and update the schema if the values are not the same.

**Comment by writeAheadLog** [comment]
> Hello!
> 
> this is caused by to older configuration in your stored settings and the typed schema we added for the new release, this is solved just by doing a clean install -> https://support.dygma.com/hc/en-us/articles/360015643358-How-do-I-clean-install-Bazecor
> 
> either way I will add checks to avoid this going forward and update the schema if the values are not the same.

@alexpargon Thanks. After I did clean install and install latest Bazecor, it works very well. 🙇

**Comment by brodie2112** [comment]
Solution worked. Thanks!
