### ISSUE TITLE
Numpad Decimal does Delete, Numpad 0 does Insert, Numpad numbers do Numrow numbers

### ISSUE THREAD

**Issue by Munzu** [Dygmalab/Bazecor#83]
**Describe the bug**
When a key is mapped to numpad decimal point, it doesn't actually do execute a numpad period but rather the Delete key.
Similarly, when a key is mapped to numpad 0, it executes the insert key.

**To Reproduce**
1. Map a key to either numpad decimal point or numpad 0
2. Go to keyboardtester.com
3. Press that mapped key
4. You should see the wrong key being pressed on keyboardtester.com

**Expected behavior**
When I press the key to which I mapped numpad decimal point or numpad 0, I expect it to type those keys. Not Delete and Insert.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.2.

**Additional context**
Tested and reproduced on both Colemak and QWERTY.

**Comment by Munzu** [comment]
Also, I'm not sure if this is related, but the numpad numbers execute just the normal numrow numbers instead of numpad numbers.

**Describe the bug**
The numpad numbers execute normal numrow numbers, not numpad numbers.

**To Reproduce**
Steps to reproduce the behavior:
1. Map a key to any of the numpad numbers
2. Go to keyboardtester.com
3. Press that mapped key
4. You should see that not the numpad number is typed, but the numrow number

**Expected behavior**
When I press the numpad numbers, I expect it to execute the numpad numbers. 
In most normal text input, it probably won't make a difference. However, some people have macros bound to numpad numbers but not numrow numbers. For example, when I played CSGO, I had weapon buy bindings bound to the numpad but not the numrow.


**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.2.

**Additional context**
Tested and reproduced on both Colemak and QWERTY.

**Comment by AlexDygma** [comment]
Hello @Munzu !

I have reviewed what you experienced and i came to the realization that the default layer 1 goes shipped with the normal numbers as the numpad disposition!

you can configure the right keys by selecting them in the `KeyConfig` button, going to the numpad section and review their behaviour with me so we can understand what is really happening?

**Comment by Munzu** [comment]
Hi Alex,

thank you, you were right. I changed them to numpad and now they work. 
Deilor also helped me figure out how to get numpad decimal point and numpad 0 to work. Turns out I have to manually turn on numlock after every reboot to have them work correctly.  

Is there a way to have those keys be available without having to manually turn on numlock?

**Comment by AlexDygma** [comment]
Hello again Munzu,

You are right, it's unintuitive that you have to activate the numlock to send a keyCode when you can configure whatever, but the fact is that it isn't the keyboard who is responsible to decide if you are pressing an arrow or a number from the numpad, but the computer it's connected to.

Basically... blame the specs.

With numlock OFF, you get navigation.  ON, you get numbers... however, the numpads are all sending the same keycodes, it's how the OS interprets them that is differentiated by numlock. 

so nothing we can do here from the Raise's side 😢 

I'll close this, if you have any good feature request, please tell it to us! we will try to make it happen 😄
