### ISSUE TITLE
Docs for using the AppImage on linux.

### ISSUE THREAD

**Issue by thedoubl3j** [Dygmalab/Bazecor#84]
**Is your feature request related to a problem? Please describe.**
Not an entirely frustrating thing if you know where to dig but some docs on how to either extract or get the appimage running on any linux distro would be good. 

**Describe the solution you'd like**
A quick way to do this is just to link to the appimage wiki talking about steps to get it into an executable state. Another way is to possibly have a separate download page from where the download's currently live and include install instructions there depending on which one is selected. 

**Describe alternatives you've considered**
Create a doc in this repo that includes the extraction/install steps and then have a link from the site here.

**Additional context**
Steps I ran were: 
```
$ ./Bazecor-0.2.2.AppImage --appimage-extract
$ cd squashfs-root/
$ ./bazecor-bin
```
Basic appimage steps that I thought I would need to run:
```
chmod +x <AppImage>
./<AppImage>
```

 Also, if docs exists for this already, then my request would be to make them more visible/discoverable. 

Absolutely love it folks, keep up the good work!

**Comment by pshanoop** [comment]
> **Is your feature request related to a problem? Please describe.**
> Not an entirely frustrating thing if you know where to dig but some docs on how to either extract or get the appimage running on any linux distro would be good.
> 
> **Describe the solution you'd like**
> A quick way to do this is just to link to the appimage wiki talking about steps to get it into an executable state. Another way is to possibly have a separate download page from where the download's currently live and include install instructions there depending on which one is selected.
> 
> **Describe alternatives you've considered**
> Create a doc in this repo that includes the extraction/install steps and then have a link from the site here.
> 
> **Additional context**
> Steps I ran were:
> 
> ```
> $ ./Bazecor-0.2.2.AppImage --appimage-extract
> $ cd squashfs-root/
> $ ./bazecor-bin
> ```
> 
> Basic appimage steps that I thought I would need to run:
> 
> ```
> chmod +x <AppImage>
> ./<AppImage>
> ```
> 
> Also, if docs exists for this already, then my request would be to make them more visible/discoverable.
> 
> Absolutely love it folks, keep up the good work!

It works fine with `chmod +x <AppImage>` on Debian sid.

**Comment by godlike64** [comment]
It used to work fine for me by doing a chmod +x of the AppImage, then running that. However, on a recently updated Gentoo box, doing that yields nothing. No error message or anything. Stracing the process makes it print the following:

`$ strace -ttfv -o /var/tmp/bazecor.out ./Bazecor-0.2.2.AppImage 
fusermount: mount failed: Operation not permitted

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
`

Which pointed me to the same thing as in this issue. Doing that I can once again run Bazecor (although it does not get integrated as in the other way, i.e. the version in krunner is still the old one).

**Comment by thedoubl3j** [comment]
@godlike64 @pshanoop thanks for the feedback. With all the linux flavors out there, having a sure fire way is almost impossible. Why I think having the major distros covered would be good. Not everyone has the time or knowledge to dig in.

**Comment by andys8** [comment]
For me it was necessary to use `sudo` and `--no-sandbox` (arch).

**Comment by siege089** [comment]
On fedora I actually ended up building from source and running `sudo ./bazecor-bin --no-sandbox` to get it to work before I found this. Definitely would help to have major distros covered.

**Comment by GazHank** [comment]
@andys8 & @siege089 I hope you will no longer need to run  sudo and --no-sandbox once the next release is pushed out as this should include the necessary fixes set the access rights for the keyboard in both normal and firmware mode.  You can check out issue https://github.com/Dygmalab/Bazecor/issues/207 and fix https://github.com/Dygmalab/Bazecor/pull/211 for more info, and especially if you would like to build from source and test the fixes before they are deployed to everyone.

If you do face issues then please let me know.  I've only tested the changes on Ubuntu so far (not my choice ;-) but am happy to fire up another distro I can help you with any issues on Arch or Fed

Cheers

Gaz

**Comment by javierguzman** [comment]
Bazecor on Linux should be executed as a normal AppImage, this is:

```
chmod +x <AppImage>
./<AppImage>

**Comment by javierguzman** [comment]
Bazecor on Linux should be executed as a normal AppImage:
```
chmod +x <AppImage>
./<AppImage>
```
You already mentioned that so I assume this was not possible due to some old Bazecor problem. Please, feel free to open if happens again.

**Comment by thedoubl3j** [comment]
@javierguzman it is working as intended now, I am guessing probably something with an older version of fedora did something unexpected.

**Comment by javierguzman** [comment]
Glad to hear @thedoubl3j !!
