### ISSUE TITLE
Naming disappears in Bazecor

### ISSUE THREAD

**Issue by tl87** [Dygmalab/Bazecor#880]
**Describe the bug**
On Linux, if you have set up names for all your super-keys and macros, and you make sure to back-up the Dygma folder in your home-folder **( ~/Dygma/ )**, where all the configufation changes are saved to. Then when/if you reinstall your OS or try to configure your keyboard from another machine, while making sure that the backed up Dygma folder is moved along and used, all the naming of super-keys and macros are removed to default naming. This makes it very hard to see what super-keys or macro does at a glance.

**To Reproduce**
1. Have super-keys and macros that are named.
2. Back up Dygma folder in your home-folder.
3. Reinstall OS or use another Linux host.
4. Make sure that the Dygma folder is copied to the new Linux host.
5. Open Bazecor and make sure under settings, that the Dygma folder is used, in your home-folder.
6. When a Defy keyboard is connected, all the super-keys and macros has non of the previous set names, that you have chosen.

**Expected behavior**
I was hoping that naming of super-keys and macros was saved to either the keyboard or the Dygma folder in your home-folder.

**Screenshots**
![image](https://github.com/user-attachments/assets/b223f633-97c1-4316-9023-24946ec6b965)
![image](https://github.com/user-attachments/assets/4dd71b43-3110-4289-9f64-215546500f6f)
![No-names](https://github.com/user-attachments/assets/b1a16fb2-9180-420b-8288-302c05b51a30)

**Desktop (please complete the following information):**
 - I've tried with Ubuntu 24.04, Debian 12, Fedora 40 Workstation and Silverblue.
 - Bazecor Version: 1.3.11, 1.4.0 and 1.4.5 (appimage)

**Additional context**
No, sorry.

**Comment by MiquelDygma** [comment]
Hi, 

My apologies for the late reply. We had a misunderstanding on the team as to who was monitoring these messages 🤦

The settings for the names are not saved in the backup folder but within the app files. 

However, there's an easy solution: restoring a backup from your backups will reinstate the names. 

Let me know if that helps

**Comment by tl87** [comment]
Hi @MiquelDygma,

That's okay, these things happens :-)

I've tried to do a restore from a back-up, but the naming is still the default naming used, non of the names I've used are restored.

As an example, below is the super-keys naming after a restore to a previous back-up:

![no-luck](https://github.com/user-attachments/assets/2d6d0f0f-ec14-4807-a849-caeb89cccb49)

**Comment by MiquelDygma** [comment]
Hi @tl87 

Thank you!

The thing is that you need to restore a backup from before you reinstalled your OS. Newer backups won't have the names.

So maybe a backup that's from early September.

**Comment by tl87** [comment]
Could a possible fix be to store the names in all the back ups? My Bazecor back up folder has alot of files (almost 500), and going through each back up to find the one with all the names, is time consuming. Also if the back up is a number of changes/key-modifications back, you would lose those, when restoring.

**Comment by MiquelDygma** [comment]
The names are stored in all the backups, as long as the names were there when the backup was created. 

You would need to restore a backup that's from before you reinstalled your OS.

Of course, restoring an older backup will revert the changes made afterward.

**Comment by tl87** [comment]
Okay, so if you have a new system or you have to do a restore and you then connect your Defy keyboard via Bazecor, the names are all gone. Then you have to remeber to restore from a previous back-up, if you have remembered to create a back up of a previous config with the names. Is it possible to save the names on the keyboard along with the config? Meaning that all the config, you have crated via Bazecor and is stored on the keyboard, also stores the names of superkeys, macros, etc? So you don't have to remember to do a restore, before you start configuring the keyboard on a new system?

**Comment by MiquelDygma** [comment]
Backups are automatically created every time you make a change, but yes, if you have a new system, you need to restore a backup to bring the name back. 

We can't store the names on the neuron because strings of text take up a lot of memory. But we're working on creating an online profile that will sync your names between Bazecor installs. Or an online version of Bazecor.

**Comment by tl87** [comment]
Okay, I'll guess restore an old back-up that has the names is the only solution for now, thanks.
