### ISSUE TITLE
Firmware update tab shows "Something went wrong"

### ISSUE THREAD

**Issue by staffann** [Dygmalab/Bazecor#905]
**Describe the bug**
"Something went wrong" when selecting the firmware tab in Bazecore, with Raise 1 keyboard.
There is a wifi icon with a line across it. I know that my Raise 1 doesn't attach wirelessly... I am on a company network, but I do have connection to internet and Bazecor just updated itself.

**To Reproduce**
1. Start Bazecore
2. Select my attached Raise to configure.
3. Select Firmware Update icon

**Expected behavior**
Information about the keyboard firmware and upgrade possibilities should appear.

**Screenshots**

[-1728630139670.log](https://github.com/user-attachments/files/17338928/-1728630139670.log)

Failed to load resource: the server responded with a status of 403 ()
index.js:8 08:58:58.412 › error when querying GitHub with Octokit
index.js:8 08:58:58.412 › 
HttpError: API rate limit exceeded for 194.39.218.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at index.js:2:36550
index.js:8 08:58:58.412 › error when filtering data from GitHub 
Error: HttpError: API rate limit exceeded for 194.39.218.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at index.js:403:62350
    at Generator.throw (<anonymous>)
    at c (index.js:403:60370)

**Desktop (please complete the following information):**
 - OS: Win11 23H2
 - Bazecor Version: 1.5.2

**Additional context**

**Comment by MiquelDygma** [comment]
Hi!

Sorry for the late reply. For the firmware update, Bazecor needs to connect to our Github repositories. That message means that it can't do that, probably because of some restriction on your company's network. 

Have you tried that at home?

Thank you!

**Comment by staffann** [comment]
Hi!
The message " API rate limit exceeded for 194.39.218.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)" didn't suggest a proxy problem to me, which is why I created the issue. The fact that Bazecore had recently updated itself also didn't point to network issues.

Anyway, the firmware update is working again, on the same network.

**Comment by MiquelDygma** [comment]
Oh I think what might be! If there are too many Github API calls from one IP, Bazecor doesn't work. It can be from Bazecor or other apps. Maybe at work there are many people using that API 😅

Thank you!
