### ISSUE TITLE
Typing greater than signs on Nordic layout

### ISSUE THREAD

**Issue by Oddj0b** [Dygmalab/Bazecor#91]
**Describe the bug**
I can't find the `greater than`, `smaller than` and the `backslash` key on the Nordic layout. It worked yesterday, but today the key mapping has changed and now I can't change it back

**To Reproduce**
1. Set your mac to Danish keyboard layout
2. Open Bazecor 0.2.2
3. Select Nordic layout
4. See that there's no key mapping for `greater than`, `smaller than`, and `backslash`

**Expected behavior**
I had the button yesterday and would expect to be able to remap those three signs.

**Screenshots**
![Screenshot 2020-10-01 at 10 31 36](https://user-images.githubusercontent.com/1084916/94786471-4f650200-03d1-11eb-87c8-ccaea87fa36b.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.5.6
 - Bazecor Version: 0.2.2

**Additional context**
These are the three signs I get when clicking the `greater than` sign:
- Unmodified: ´
- With option: '
- With option + shift: ⁄
- With control + option: ´
- With control + shift: ´

**Comment by mortenlerudjordet** [comment]
Just use "NON-US \" and you are good to go.
The one in the far right in your picture.

**Comment by Oddj0b** [comment]
Thanks @mortenlerudjordet, that worked! Now I have to find out why the key mapping changed seemingly on the fly.
