### ISSUE TITLE
Sudden, unexpected release of the "press" macro key

### ISSUE THREAD

**Issue by Mattchine** [Dygmalab/Bazecor#917]
**Describe the bug**  
Setting a macro key with the "press" action is supposed to behave like a "hold" action (i.e., it should not release), but instead, it behaves as "press and release."

**To Reproduce**  
1. Set up a macro key with the "press" action.
2. Try using the macro key by holding it down.

**Expected behavior**  
The macro key should function as a "hold" when set to "press."

**Screenshots**  
![Holding shift then holding macro](https://github.com/user-attachments/assets/835eedbd-8f37-4344-83a8-a2b40163daa3)  
- First, I am holding the shift key, which is evident from the keycast showing that the key is pressed for a while.  
- Then, when I hold the macro key (a few times), you can see that it unexpectedly releases immediately after being pressed.

**Desktop (please complete the following information):**
- **OS**: macOS 15.0.1
- **Bazecor Version**: 1.0.12 beta firmware

**Comment by MiquelDygma** [comment]
I'm afraid macros don't behave that way. You can't "hold" them. It's just a sequence of key presses. 

What you might want is a shortcut. 

Here's a screenshot that recreates what you want from that macro:

![Screenshot 2024-10-21 at 16 07 14](https://github.com/user-attachments/assets/3bb7c862-c069-4b90-a026-0f200064dd58)

Let me know if that worksi

**Comment by Mattchine** [comment]
Thank you. That's solve the problem.
