### ISSUE TITLE
Optionally indicate on the keyboard which layer number is current

### ISSUE THREAD

**Issue by ASKemp** [Dygmalab/Bazecor#94]
**Is your feature request related to a problem? Please describe.**
It can be difficult to know which layer you currently have selected, a method to indicate on the keyboard would be helpful.

**Describe the solution you'd like**
When selecting a layer, briefly show the layer number by flashing or highlighting the corresponding number key.
Additionally, a long press of the LED key could do the same.

**Comment by javierguzman** [comment]
This can be done using different colours for different layers. Also, we plan to make an overlay so users can see a keyboard in the screen while typing
