### ISSUE TITLE
Allow reading battery percentage from commandline

### ISSUE THREAD

**Issue by mimre25** [Dygmalab/Bazecor#941]
**Is your feature request related to a problem? Please describe.**
I would like to see my keyboard's battery percentage in my polybar setup. 
To do that, I need some form of accessing the battery percentage from the commandline

**Describe the solution you'd like**
A commandline flag to bazecor that let's one just read the battery percentage.
eg
```sh
> bazecor --battery
Raise 2 {
  "left": .2,
  "right": .3
}
```

**Describe alternatives you've considered**
I did a short source-dive, but haven't pinpointed the location yet where the battery percentage is read.

I also considered using udev and other system tools, but since bazecor has the capability already, why not just expose it via a commandline flag?

**Comment by alexpargon** [comment]
Hey there @mimre25!

you can access the battery readings by using these commands:

https://github.com/Dygmalab/Bazecor/blob/c34efdd6b7d8ffcb897cde72a0e839ff9dc654aa/src/renderer/modules/Battery/BatteryStatus.tsx#L148C6-L152C94

 They are not yet documented here, but will be: 
 https://github.com/Dygmalab/Bazecor/blob/development/FOCUS_API.md
 
 I will add them to the next release.

**Comment by mimre25** [comment]
For anyone interested in doing something similar, I've written a python script that reads the battery percentage using `pyserial-asyncio`

```py
from serial_asyncio import open_serial_connection
import asyncio

async def read(reader):
        left_pct = int(await reader.readline())
        _ = await reader.readline()  # ignore the `.` line
        right_pct = int(await reader.readline())
        _ = await reader.readline()  # ignore the `.` line
        print(f"{left_pct}/{right_pct}%")


async def write(writer):
    writer.write(b"wireless.battery.left.level\n")
    writer.write(b"wireless.battery.right.level\n")
    await writer.drain()


async def main():
    reader, writer = await open_serial_connection(url='/dev/ttyACM0')
    await asyncio.gather(write(writer), read(reader))


if __name__ == "__main__":
    asyncio.run(main())
```

If anyone is curious on how to use this with polybar, please let me know, then I'll post a link to my polybar setup using an adaptation of this script.

Thank you Alex for pointing me to the API docs :slightly_smiling_face:
