### ISSUE TITLE
Custom colours not saving

### ISSUE THREAD

**Issue by ASKemp** [Dygmalab/Bazecor#95]
When adding a custom colour to the right hand side and then allocating it to a key or underglow, it works on export but seems to then be lost and defaults back to the previous colour.

**Comment by AlexDygma** [comment]
Hello @ASKemp !

can you please try this [with the newest version of bazecor?](https://github.com/Dygmalab/Bazecor/releases/tag/bazecor-0.2.4)

if you keep having the same or other problems, please fill a full bug report so we can start working on it!

i'll close this for the time being as the information is not sufficient to trace the bug.
