### ISSUE TITLE
Transperant lighting color for keys

### ISSUE THREAD

**Issue by martinruefenacht** [Dygmalab/Bazecor#950]
**Is your feature request related to a problem? Please describe.**
Not exactly although it is quite disorienting. When switching layers we can purposefully assign transperant keys so they fall to the next lower layer defined key in that position. **We can't do this with the color lighting.** My key layouts are colored according to function, so when I have a transperant key to refer to a function on a different layer I would expect the color to match.

I can do this manually, but that is the same argument as with transperant function of keys.

**Describe the solution you'd like**

Add a color called **transperant** (obviously not modifiable), which then shows the color of which ever one it reduces to on lower levels. I assume this is baked and not done dynamically on the neuron for the key function, so the same preprocess before saving can be done with key color as with key functions.

**Describe alternatives you've considered**

I guess to do it manually, but then what is the point of function transperancy?

**Additional context**
This would just be a nice QoL improvement.

**Comment by MiquelDygma** [comment]
Thank you, we'll explore if this possible within the firmware and/or how difficult it would be to add it.

**Comment by martinruefenacht** [comment]
Good to hear! If you have time to describe, how is the transparent key functionality implemented?

Is it dynamic on the neuron, so when on a layer a transplant key is pressed does it translate that to a different layer? Or is it implemented such that every layer gets baked to a fixed function key (and transparency doesn't exist at runtime)?

**Comment by MiquelDygma** [comment]
It's dynamic on the neuron. The transparent key changes depending on what layer you're coming from.

**Comment by martinruefenacht** [comment]
Is this to save memory on the neuron? Or another motivation? (If you can say :D)

**Comment by MiquelDygma** [comment]
It's designed that way because if we baked it, the transparent key wouldn't work as intended. Transparent means that it's the same key as the layer you're coming from. It will be a different key if you're coming from layer 1 or layer 4.

**Comment by martinruefenacht** [comment]
Thanks for the explanation! In that case my manual solution doesn't work at all and the requested functionality is not able to be implemented by a user.

**Comment by MiquelDygma** [comment]
If you have it configured so your base layer is always layer one, you could manually fake it. But if you have a more complex layer navigation system, then no...

**Comment by MiquelDygma** [comment]
Hi!

I talked with the dev team, and they told me that this would be a very complex firmware implementation and that it could also lead to some UX inconsistencies. 

For now, we haven't added it to the roadmap.

Best,
