### ISSUE TITLE
Default behavior of superkeys

### ISSUE THREAD

**Issue by ExposedCat** [Dygmalab/Bazecor#958]
Writing this on a new Raise 2 ❤️ 

**Is your feature request related to a problem? Please describe.**
Setting up a superkey for hold & tap breaks default behavior for double tap (and all the other handlers) 

**Describe the solution you'd like**
It would be nice to have "transparent" option instead of "no key"

**Describe alternatives you've considered**
Not using superkeys

**Additional context**
None

**Comment by MiquelDygma** [comment]
Hi!

Could you share a bit more in detail how you have configured the superkey?

Thanks!

**Comment by ExposedCat** [comment]
@MiquelDygma it doesn't really matter. The thing is that I want default behavior for everything except of, for instance, hold. This would mean that double click will type the letter 2 times which is a default double-click behavior; however if I use superkey and configure a letter for single tap, another letter for hold - then I have no way to setup double-tap to type a letter twice

**Comment by MiquelDygma** [comment]
If you set something on tap and something on hold, and you double-tap, you should get the tap two times. 

Have you tried adjusting the timings on preferences?

**Comment by ExposedCat** [comment]
@MiquelDygma I'm really sorry but seems that I was mistaken - it works as expected 😮
