### ISSUE TITLE
When selecting a key to edit, its colour is not selected

### ISSUE THREAD

**Issue by ASKemp** [Dygmalab/Bazecor#96]
May be bug or as intended, in which case would then be a feature request.

When selecting a key to edit, then current colour allocated to the key should be selected/highlighted in the colour pallet.

**Comment by AlexDygma** [comment]
Hello @ASKemp !

yea, you are right, this is not intended and as you say, if you have a color multiple times or very similar ones it can be confusing to not have a reference of what color form the palette is actually selected for that key.

ill put this in the milestone for the 0.2.5 version.

**Comment by AlexDygma** [comment]
After checking this functionality, it's already in place! 

you need to press shift key while clicking any key in the layout and it will select the color at the same time.

test it when you can! 😄
