### ISSUE TITLE
Dygma Raise press on greater than and smaller than result in wrong symbols on Macbook

### ISSUE THREAD

**Issue by Mauge9638** [Dygmalab/Bazecor#961]
**Describe the bug**

**To Reproduce**
1. Connect Dygma Raise.
2. Have the setup as seen in screenshot.
3. Press the key(s) where you except greater than ">" and less than "<" and instead get § for > $ for <.

**Expected behavior**
I expect the symbols to be correct and outputted as Bazecor is setup to.

**Screenshots**
![Screenshot 2024-11-29 at 09 06 14](https://github.com/user-attachments/assets/e069d576-bb5d-43d1-b143-81197081ef58)

**Desktop (please complete the following information):**
 - OS: [macOS Sequoia 15.1.1]
 - Bazecor Version: [v1.0.12-beta] (also tried v0.3.7) and (v1.0.11-beta)

**Additional context**
I have used this layout on Linux (Ubuntu) and Windows and it works without any issues.

**Comment by magnusstuart** [comment]
Okay i found a (stupid) fix, i have my keyboard connected to the mac through a KVM in my monitor (so i can switch between my desktop windows and macbook easily) and for some reason, the keyboard identifying stuff on Mac messes up unless it is connected directly to the Macbook.
