### ISSUE TITLE
Group the layer related key function together in the key config modal

### ISSUE THREAD

**Issue by ASKemp** [Dygmalab/Bazecor#97]
The layout  of the key config modal seems a little confusing, the commands related to layer functions should at least be grouped together for consistency and could be simplified by using a single group of numbers to select the layer and radio buttons to choose the functionality, i.e. osl, shift to, move to, lock to

**Comment by alexpargon** [comment]
This has been solved with the new UI in Bazecor 1.0 stable and onwards.
